### ISSUE TITLE
Spark 3 support

### ISSUE THREAD

**Issue by chengyineng38** [microsoft/SynapseML#1135]
Spark 3 has been released for over a year now. Is there a timeline when lightgbm can support Spark 3?

**Comment by imatiach-msft** [comment]
@chengyineng38 mmlspark does support spark 3 on master.  mmlspark hasn't had an official release yet since spark 3 support was added (rc3 release was still on spark 2.4).  I'm not sure about the exact timeline.

**Comment by sa-** [comment]
Also interested in Spark 3 support here :)

**Comment by memoryz** [comment]
Linking this comment for some context:
https://github.com/Azure/mmlspark/issues/1114#issuecomment-880249564

**Comment by limbXo** [comment]
> @chengyineng38 mmlspark does support spark 3 on master. mmlspark hasn't had an official release yet since spark 3 support was added (rc3 release was still on spark 2.4). I'm not sure about the exact timeline for the next official release, but you can use any of the builds on master.

Thanks for the advice. And how do I find maven coordinates of builds on master?

**Comment by mhamilton723** [comment]
@limbXo please see this page for install of newer version (Spark 3 compatible)
