### ISSUE TITLE
Dependency conflict when downloading with mvn plugin

### ISSUE THREAD

**Issue by bipin2295** [microsoft/SynapseML#1166]
I'm trying to download the dependency and jar by using :
`mvn dependency:get -DremoteRepositories="https://mmlspark.azureedge.net/maven" -Dartifact="com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-43-54379bf7-SNAPSHOT"
` 
It's downloading jars for scala-reflect-2.12.10.jar

However, when I'm using spark-submit command with options 
`--repositories https://mmlspark.azureedge.net/maven --packages com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-43-54379bf7-SNAPSHOT`, 
it's downloading the scala-reflect-2.12.4.jar

Due to this, when I'm trying to pre-fetch all the packages and jars before spark execution, it's failing due to this conflict

**Comment by memoryz** [comment]
can you submit with `--packages com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-43-54379bf7-SNAPSHOT,org.scala-lang:scala-reflect:2.12.10`?

**Comment by mhamilton723** [comment]
Please feel free to re-open if needed
