### ISSUE TITLE
How to locate URL of Jar Files?

### ISSUE THREAD

**Issue by AllardJM** [microsoft/SynapseML#1180]
In my environment it seems I need to locate the actual jar file to use MMLSPARK. For example: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark_2.11/1.0.0-rc3/mmlspark_2.11-1.0.0-rc3.jar

How can I find the jar files that are related to other versions like the snapshot:
com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-24-495af3e4-SNAPSHOT

Thanks!

**Comment by boltzmann-brain** [comment]
I've been following the URL formats in [this comment](https://github.com/microsoft/SynapseML/issues/1119#issuecomment-879958859).

**Comment by mhamilton723** [comment]
Thanks for answering this @boltzmann-brain. Please feel free to re-open if needed
