### ISSUE TITLE
Latest version of RC3 does not appear to be available on your maven site for Spark 2.11 or 2.12

### ISSUE THREAD

**Issue by DCameronMauch** [microsoft/SynapseML#1187]
% export COURSIER_REPOSITORIES="https://mmlspark.azureedge.net/maven"

% bin/cs -h
Coursier 2.0.16
Usage: cs [options] [command] [command-options]

Available commands: bootstrap, channel, complete, fetch, get, install, java, java-home, launch, list, publish, resolve, setup, uninstall, update, search

Type  cs command --help  for help on an individual command

% bin/cs fetch com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc3-178-66105775-SNAPSHOT
Resolution error: Error downloading com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc3-178-66105775-SNAPSHOT
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark_2.11/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark_2.11-1.0.0-rc3-178-66105775-SNAPSHOT.pom

% bin/cs fetch com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-178-66105775-SNAPSHOT
Resolution error: Error downloading com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-178-66105775-SNAPSHOT
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark_2.12/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark_2.12-1.0.0-rc3-178-66105775-SNAPSHOT.pom

**Comment by DCameronMauch** [comment]
But I can get an older version, so the tool and repo work:

% bin/cs fetch com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-94-0632f1bf-SNAPSHOT

**Comment by DCameronMauch** [comment]
Why does your Maven server not show versions available, like central does?

% bin/cs complete com.microsoft.ml.spark:mmlspark_2.12:
% bin/cs complete com.microsoft.ml.spark:mmlspark_2.11:
0.18.0
0.18.1

The only ones it finds is the super old ones from central.  Nothing from your Maven server at all.

**Comment by memoryz** [comment]
The maven coordinate for latest version is `com.microsoft.ml.spark:mmlspark:{version}`.

**Comment by DCameronMauch** [comment]
I had tried that, but still doesn't work:

cmauch@Douglass-MacBook-Pro ~ % bin/cs fetch com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3
Resolution error: Error downloading com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3
  not found: https://repo1.maven.org/maven2/com/microsoft/ml/spark/mmlspark_2.12/1.0.0-rc3/mmlspark_2.12-1.0.0-rc3.pom
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark_2.12/1.0.0-rc3/mmlspark_2.12-1.0.0-rc3.pom
cmauch@Douglass-MacBook-Pro ~ % bin/cs fetch com.microsoft.ml.spark:mmlspark_2.12:1.0.0
Resolution error: Error downloading com.microsoft.ml.spark:mmlspark_2.12:1.0.0
  not found: https://repo1.maven.org/maven2/com/microsoft/ml/spark/mmlspark_2.12/1.0.0/mmlspark_2.12-1.0.0.pom
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark_2.12/1.0.0/mmlspark_2.12-1.0.0.pom

**Comment by memoryz** [comment]
Use the master branch version instead, e.g. `1.0.0-rc3-178-66105775-SNAPSHOT`.

**Comment by DCameronMauch** [comment]
It appears I can get the .pom file for that, but not the JAR itself, or any of the dependencies:

% bin/cs fetch com.microsoft.ml.spark:mmlspark:1.0.0-rc3-178-66105775-SNAPSHOT
https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.pom
  100.0% [##########] 4.7 KiB (9.4 KiB / s)
Resolution error: Error downloading com.microsoft.ml.spark:mmlspark-cognitive;sbtVersion=1.0;scalaVersion=2.12:1.0.0-rc3-178-66105775-SNAPSHOT
  not found: https://repo1.maven.org/maven2/com/microsoft/ml/spark/mmlspark-cognitive_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.pom
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark-cognitive_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.pom
Error downloading com.microsoft.ml.spark:mmlspark-opencv;sbtVersion=1.0;scalaVersion=2.12:1.0.0-rc3-178-66105775-SNAPSHOT
  not found: https://repo1.maven.org/maven2/com/microsoft/ml/spark/mmlspark-opencv_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-opencv-1.0.0-rc3-178-66105775-SNAPSHOT.pom
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark-opencv_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-opencv-1.0.0-rc3-178-66105775-SNAPSHOT.pom
Error downloading com.microsoft.ml.spark:mmlspark-vw;sbtVersion=1.0;scalaVersion=2.12:1.0.0-rc3-178-66105775-SNAPSHOT
  not found: https://repo1.maven.org/maven2/com/microsoft/ml/spark/mmlspark-vw_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-vw-1.0.0-rc3-178-66105775-SNAPSHOT.pom
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark-vw_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-vw-1.0.0-rc3-178-66105775-SNAPSHOT.pom
Error downloading com.microsoft.ml.spark:mmlspark-core;sbtVersion=1.0;scalaVersion=2.12:1.0.0-rc3-178-66105775-SNAPSHOT
  not found: https://repo1.maven.org/maven2/com/microsoft/ml/spark/mmlspark-core_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-core-1.0.0-rc3-178-66105775-SNAPSHOT.pom
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark-core_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-core-1.0.0-rc3-178-66105775-SNAPSHOT.pom
Error downloading com.microsoft.ml.spark:mmlspark-lightgbm;sbtVersion=1.0;scalaVersion=2.12:1.0.0-rc3-178-66105775-SNAPSHOT
  not found: https://repo1.maven.org/maven2/com/microsoft/ml/spark/mmlspark-lightgbm_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-lightgbm-1.0.0-rc3-178-66105775-SNAPSHOT.pom
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark-lightgbm_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-lightgbm-1.0.0-rc3-178-66105775-SNAPSHOT.pom
Error downloading com.microsoft.ml.spark:mmlspark-deep-learning;sbtVersion=1.0;scalaVersion=2.12:1.0.0-rc3-178-66105775-SNAPSHOT
  not found: https://repo1.maven.org/maven2/com/microsoft/ml/spark/mmlspark-deep-learning_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-deep-learning-1.0.0-rc3-178-66105775-SNAPSHOT.pom
  not found: https://mmlspark.azureedge.net/maven/com/microsoft/ml/spark/mmlspark-deep-learning_2.12_1.0/1.0.0-rc3-178-66105775-SNAPSHOT/mmlspark-deep-learning-1.0.0-rc3-178-66105775-SNAPSHOT.pom

**Comment by tadaoisgod** [comment]
![image](https://user-images.githubusercontent.com/3580029/134024492-103f6d34-09b6-44b1-9d69-f779ed679286.png)
Same here, I'm trying to install the latest snapshot and it isn't recognizing the library.

**Comment by DCameronMauch** [comment]
@tadaoisgod looks like you used default repository.  Can you try it again using theirs:  "https://mmlspark.azureedge.net/maven"?  Just to make sure.

**Comment by tadaoisgod** [comment]
Same thing. Tried both links with and without Spark version type.
![image](https://user-images.githubusercontent.com/3580029/134049697-b5c8c9ef-1d66-4a55-adb8-8f92484dde3a.png)
![image](https://user-images.githubusercontent.com/3580029/134049822-9cb9db1b-f54b-42d0-94ea-d4a896b0ab32.png)

**Comment by memoryz** [comment]
@tadaoisgod 

That's weird... I just tried in an Azure Databricks cluster (tried both 7.3 LTS and 9.1 Beta), and the library installed correctly:
![image](https://user-images.githubusercontent.com/6992432/134068762-4d2b753b-f37d-435e-8732-b9e7c524d13d.png)

The maven coordinate should be `com.microsoft.ml.spark:mmlspark:1.0.0-rc3-178-66105775-SNAPSHOT`, without the `_2.12`  part in the artifactId.

In the driver Log4j output, I see the following logs:

```
21/09/20 20:14:20 INFO DriverCorral: AttachLibraries - candidate libraries: List(JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE))
21/09/20 20:14:20 INFO DriverCorral: AttachLibraries - new libraries to install (including resolved dependencies): List(JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE))
21/09/20 20:14:20 INFO SharedDriverContext: attachLibrariesToSpark JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE)
21/09/20 20:14:20 INFO LibraryDownloadManager: Downloading a library that was not in the cache: JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE)
21/09/20 20:14:20 INFO LibraryDownloadManager: Attempt 1: wait until library JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE) is downloaded
21/09/20 20:14:21 INFO LibraryDownloadManager: Downloaded library JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE) as local file /local_disk0/tmp/addedFile640087740138982577mmlspark_1_0_0_rc3_178_66105775_SNAPSHOT-12199.jar in 716 milliseconds
21/09/20 20:14:21 INFO SharedDriverContext: Successfully saved library JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE) to local file /local_disk0/tmp/addedFile640087740138982577mmlspark_1_0_0_rc3_178_66105775_SNAPSHOT-12199.jar 
21/09/20 20:14:21 INFO SparkContext: Added file /local_disk0/tmp/addedFile640087740138982577mmlspark_1_0_0_rc3_178_66105775_SNAPSHOT-12199.jar at spark://10.139.64.43:39645/files/addedFile640087740138982577mmlspark_1_0_0_rc3_178_66105775_SNAPSHOT-12199.jar with timestamp 1632168861104
21/09/20 20:14:21 INFO Utils: Copying /local_disk0/tmp/addedFile640087740138982577mmlspark_1_0_0_rc3_178_66105775_SNAPSHOT-12199.jar to /local_disk0/spark-bf55c5b2-64cf-4455-9cbf-2717d15ecc97/userFiles-fa5b68e2-89ad-4d10-9f06-f044d76e2400/addedFile640087740138982577mmlspark_1_0_0_rc3_178_66105775_SNAPSHOT-12199.jar
21/09/20 20:14:21 INFO SparkContext: Added JAR /local_disk0/tmp/addedFile640087740138982577mmlspark_1_0_0_rc3_178_66105775_SNAPSHOT-12199.jar at spark://10.139.64.43:39645/jars/addedFile640087740138982577mmlspark_1_0_0_rc3_178_66105775_SNAPSHOT-12199.jar with timestamp 1632168861140
21/09/20 20:14:21 INFO SharedDriverContext: Successfully attached library dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar to Spark
21/09/20 20:14:21 INFO LibraryState: Successfully attached library dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-1.0.0-rc3-178-66105775-SNAPSHOT.jar

......

21/09/20 20:14:23 INFO DriverCorral: AttachLibraries - candidate libraries: List(JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE))
21/09/20 20:14:23 INFO DriverCorral: AttachLibraries - new libraries to install (including resolved dependencies): List(JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE))
21/09/20 20:14:23 INFO SharedDriverContext: attachLibrariesToSpark JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE)
21/09/20 20:14:23 INFO LibraryDownloadManager: Downloading a library that was not in the cache: JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE)
21/09/20 20:14:23 INFO LibraryDownloadManager: Attempt 1: wait until library JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE) is downloaded
21/09/20 20:14:23 INFO LibraryDownloadManager: Downloaded library JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE) as local file /local_disk0/tmp/addedFile8662568572195655824mmlspark_cognitive_1_0_0_rc3_178_66105775_SNAPSHOT-ce179.jar in 125 milliseconds
21/09/20 20:14:23 INFO SharedDriverContext: Successfully saved library JavaJarId(dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar,,NONE) to local file /local_disk0/tmp/addedFile8662568572195655824mmlspark_cognitive_1_0_0_rc3_178_66105775_SNAPSHOT-ce179.jar 
21/09/20 20:14:23 INFO SparkContext: Added file /local_disk0/tmp/addedFile8662568572195655824mmlspark_cognitive_1_0_0_rc3_178_66105775_SNAPSHOT-ce179.jar at spark://10.139.64.43:39645/files/addedFile8662568572195655824mmlspark_cognitive_1_0_0_rc3_178_66105775_SNAPSHOT-ce179.jar with timestamp 1632168863179
21/09/20 20:14:23 INFO Utils: Copying /local_disk0/tmp/addedFile8662568572195655824mmlspark_cognitive_1_0_0_rc3_178_66105775_SNAPSHOT-ce179.jar to /local_disk0/spark-bf55c5b2-64cf-4455-9cbf-2717d15ecc97/userFiles-fa5b68e2-89ad-4d10-9f06-f044d76e2400/addedFile8662568572195655824mmlspark_cognitive_1_0_0_rc3_178_66105775_SNAPSHOT-ce179.jar
21/09/20 20:14:23 INFO SparkContext: Added JAR /local_disk0/tmp/addedFile8662568572195655824mmlspark_cognitive_1_0_0_rc3_178_66105775_SNAPSHOT-ce179.jar at spark://10.139.64.43:39645/jars/addedFile8662568572195655824mmlspark_cognitive_1_0_0_rc3_178_66105775_SNAPSHOT-ce179.jar with timestamp 1632168863195
21/09/20 20:14:23 INFO SharedDriverContext: Successfully attached library dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar to Spark
21/09/20 20:14:23 INFO LibraryState: Successfully attached library dbfs:/FileStore/jars/maven/com/microsoft/ml/spark/mmlspark-cognitive-1.0.0-rc3-178-66105775-SNAPSHOT.jar
```
I'm not sure why your Databricks cluster would resolve to `com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-178-66105775-SNAPSHOT`, but this coordinate is wrong. What's cloud provider you're using here? and what's the cluster version?

**Comment by DCameronMauch** [comment]
I tried it without the _2.12, same thing.  See above.  Also, how then would I differentiate between the Scala 2.11 and 2.12 versions, which are definitely not interchangable.

**Comment by tadaoisgod** [comment]
@memoryz I'm running a Databricks-managed workspace, with the `9.0 ML (includes Apache Spark 3.1.2, GPU, Scala 2.12)` cluster.

**Comment by mhamilton723** [comment]
@DCameronMauch latest versions are 2.12 only. We are looking into sbt to see if we can re-add the _2.11 prefixes

**Comment by tadaoisgod** [comment]
I ran the install again with the same coordinates and repository, and it worked! 
Maybe it was some kind of cached requirement going awry?

![image](https://user-images.githubusercontent.com/3580029/134072989-91a8572f-e88e-4a47-912d-855d236b4b39.png)

**Comment by memoryz** [comment]
@DCameronMauch 
I cannot make it work with Coursier, but here is a somewhat ugly workaround to fetch individual components:
```
cs fetch com.microsoft.ml.spark:mmlspark-core:1.0.0-rc3-178-66105775-SNAPSHOT -r https://mmlspark.azureedge.net/maven
cs fetch com.microsoft.ml.spark:mmlspark-cognitive:1.0.0-rc3-178-66105775-SNAPSHOT -r https://mmlspark.azureedge.net/maven --exclude com.microsoft.ml.spark:mmlspark-core
cs fetch com.microsoft.ml.spark:mmlspark-opencv:1.0.0-rc3-178-66105775-SNAPSHOT -r https://mmlspark.azureedge.net/maven --exclude com.microsoft.ml.spark:mmlspark-core
cs fetch com.microsoft.ml.spark:mmlspark-vw:1.0.0-rc3-178-66105775-SNAPSHOT -r https://mmlspark.azureedge.net/maven --exclude com.microsoft.ml.spark:mmlspark-core
cs fetch com.microsoft.ml.spark:mmlspark-lightgbm:1.0.0-rc3-178-66105775-SNAPSHOT -r https://mmlspark.azureedge.net/maven --exclude com.microsoft.ml.spark:mmlspark-core
cs fetch com.microsoft.ml.spark:mmlspark-deep-learning:1.0.0-rc3-178-66105775-SNAPSHOT -r https://mmlspark.azureedge.net/maven --exclude com.microsoft.ml.spark:mmlspark-core --exclude com.microsoft.ml.spark:mmlspark-opencv
```

Meanwhile, I believe @mhamilton723 will look into a better solution. Closing the issue for now.
