### ISSUE TITLE
Obtain shaded jar for latest build?

### ISSUE THREAD

**Issue by cscn** [microsoft/SynapseML#1201]
Hi mmlspark team! I'm currently trying to run mmlspark (specifically the `mmlspark.exlainers` subpackage) on a Qubole spark cluster. The Qubole cluster is finicky in that I seem unable to provide a `--packages` argument for installing mmlspark, and instead must rely on passing a `.jar` file. From local testing, I found that the latest snapshot  appears to have the `explainers` subpackage: `com.microsoft.ml.spark:mmlspark:1.0.0-rc3-179-327be83c-SNAPSHOT`

Is there any way to obtain a `.jar` file with mmlspark and all dependencies, which if provided to the cluster would mimic the behavior of passing the the above maven coordinates as the `--packages` arg? I've tried downloading, unpacking, and repacking all jars listed during pyspark initialization into a single jar then supplying that to my cluster, but received this error each time:
```
>>> from mmlspark.explainers import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mmlspark.explainers'
```

I've also tried downloading all the individual jar files into the pyspark working directory and supplying all of them in comma-separated format as the `--jars` argument, which yields the same `ModuleNotFoundError`. I don't think it's an environment issue, as supplying the the maven coords above as the `--packages` argument results in the correct behavior. 

Would appreciate any/all help!

**Comment by mhamilton723** [comment]
Please feel free to re-open if needed
