### ISSUE TITLE
SynapseML jar is missing code

### ISSUE THREAD

**Issue by cosmincatalin** [microsoft/SynapseML#1227]
The jar at https://mmlspark.azureedge.net/maven/com/microsoft/azure/synapseml/0.9.1/synapseml-0.9.1.jar is only a few bytes and contains just meta information. As a result, when using it, imports break.

Where can one go to get the jar with the actual code?

**Comment by mhamilton723** [comment]
@cosmincatalin this jar just contains pointers to the sub-package jars and you can see this in the pom.xml here:
https://mmlspark.blob.core.windows.net/maven/com/microsoft/azure/synapseml/0.9.1/synapseml-0.9.1.pom

SynapseML isn't designed to be easily installable by uploading Jars as it has several dependencies. Please consider installing via spark.jars.packages using maven coordinates. Hope this helps and feel free to re-open if needed

**Comment by liuyonglang** [comment]
> @cosmincatalin this jar just contains pointers to the sub-package jars and you can see this in the pom.xml here: https://mmlspark.blob.core.windows.net/maven/com/microsoft/azure/synapseml/0.9.1/synapseml-0.9.1.pom
> 
> SynapseML isn't designed to be easily installable by uploading Jars as it has several dependencies. Please consider installing via spark.jars.packages using maven coordinates. Hope this helps and feel free to re-open if needed

my machines have no network access, how can i install the synapseml on spark cluster?  thanks
