### ISSUE TITLE
@cosmincatalin this jar just contains pointers to the sub-package jars and you can see this in the pom.xml here:

### ISSUE THREAD

**Issue by liuyonglang** [microsoft/SynapseML#1254]
@cosmincatalin this jar just contains pointers to the sub-package jars and you can see this in the pom.xml here:
https://mmlspark.blob.core.windows.net/maven/com/microsoft/azure/synapseml/0.9.1/synapseml-0.9.1.pom

SynapseML isn't designed to be easily installable by uploading Jars as it has several dependencies. Please consider installing via spark.jars.packages using maven coordinates. Hope this helps and feel free to re-open if needed

_Originally posted by @mhamilton723 in https://github.com/microsoft/SynapseML/issues/1227#issuecomment-960261697_

**Comment by liuyonglang** [comment]
My machines have no network access, How can I install the synapseml on spark cluster?  mmlspak 0.18 in one jar ,I can use --jar upload to install. Thanks for your attention.

**Comment by memoryz** [comment]
Hi @liuyonglang, even with mmlspark 0.18, not all dependencies are packaged into one jar. There are many external dependencies that have to be installed at Spark runtime. It may have worked for you because you were not calling into these dependencies.
One thing you may want to try is to install all the dependencies in a docker image, export the image to your offline machine, and run through docker.

**Comment by mhamilton723** [comment]
@liuyonglang, perhaps you can clone the repository locally and use sbt assembly to make a fat jar?

**Comment by wisundstrom** [comment]
@liuyonglang I'm in a similar situation on a spark cluster with no internet access, have you found a solution?

@mhamilton723 I'll play around with that idea and see if I can get it to work

**Comment by cosmincatalin** [comment]
Can we get this in Maven Central. I think we can all agree that would be easiest for everybody, with no obvious downsides?

**Comment by mhamilton723** [comment]
@cosmincatalin that is coming in our next release if all goes according to plan!

**Comment by mhamilton723** [comment]
Feel free to re-open if needed

**Comment by liuyonglang** [comment]
> @liuyonglang I'm in a similar situation on a spark cluster with no internet access, have you found a solution?
> 
> @mhamilton723 I'll play around with that idea and see if I can get it to work

I clone this locally and use sbt build some jars。Then I add all jars to spark dependency。

**Comment by liuyonglang** [comment]
> @liuyonglang I'm in a similar situation on a spark cluster with no internet access, have you found a solution?
> 
> @mhamilton723 I'll play around with that idea and see if I can get it to work

I clone this locally and use sbt build some jars。Then I add all jars to spark dependency。

**Comment by liuyonglang** [comment]
> @liuyonglang I'm in a similar situation on a spark cluster with no internet access, have you found a solution?
> 
> @mhamilton723 I'll play around with that idea and see if I can get it to work

I clone this locally and use sbt build some jars。Then I add all jars to spark dependency。
