### ISSUE TITLE
Unable to install SynapseML on Databricks

### ISSUE THREAD

**Issue by zwag20** [microsoft/SynapseML#1257]
**Describe the bug**
I am unable to install SynapseML on DataBricks. It fails with the following message

Library resolution failed. Cause: java.lang.RuntimeException: unresolved dependency: com.microsoft.azure:synapseml:0.9.3: not found at com.databricks.libraries.server.MavenInstaller.doDownloadMavenPackages(MavenLibraryResolver.scala:437) at com.databricks.libraries.server.MavenInstaller.$anonfun$downloadMavenPackages$2(MavenLibraryResolver.scala:381) at com.databricks.backend.common.util.FileUtils$.withTemporaryDirectory(FileUtils.scala:466) at com.databricks.libraries.server.MavenInstaller.$anonfun$downloadMavenPackages$1(MavenLibraryResolver.scala:380) at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:389) at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:478) at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$4(UsageLogging.scala:498) at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:263) at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:261) at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:258) at com.databricks.libraries.server.MavenInstaller.withAttributionContext(MavenLibraryResolver.scala:57) at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:299) at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:291) at com.databricks.libraries.server.MavenInstaller.withAttributionTags(MavenLibraryResolver.scala:57) at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:473) at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:398) at com.databricks.libraries.server.MavenInstaller.recordOperationWithResultTags(MavenLibraryResolver.scala:57) at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:389) at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:361) at com.databricks.libraries.server.MavenInstaller.recordOperation(MavenLibraryResolver.scala:57) at com.databricks.libraries.server.MavenInstaller.downloadMavenPackages(MavenLibraryResolver.scala:379) at com.databricks.libraries.server.MavenInstaller.downloadMavenPackagesWithRetry(MavenLibraryResolver.scala:137) at com.databricks.libraries.server.MavenInstaller.resolveMavenPackages(MavenLibraryResolver.scala:113) at com.databricks.libraries.server.MavenLibraryResolver.resolve(MavenLibraryResolver.scala:44) at com.databricks.libraries.server.ManagedLibraryManager$GenericManagedLibraryResolver.resolve(ManagedLibraryManager.scala:243) at com.databricks.libraries.server.ManagedLibraryManagerImpl$.$anonfun$resolvePrimitives$1(ManagedLibraryManagerImpl.scala:1222) at com.databricks.libraries.server.ManagedLibraryManagerImpl$.$anonfun$resolvePrimitives$1$adapted(ManagedLibraryManagerImpl.scala:1217) at scala.collection.Iterator.foreach(Iterator.scala:943) at scala.collection.Iterator.foreach$(Iterator.scala:943) at scala.collection.AbstractIterator.foreach(Iterator.scala:1431) at scala.collection.IterableLike.foreach(IterableLike.scala:74) at scala.collection.IterableLike.foreach$(IterableLike.scala:73) at scala.collection.AbstractIterable.foreach(Iterable.scala:56) at com.databricks.libraries.server.ManagedLibraryManagerImpl$.resolvePrimitives(ManagedLibraryManagerImpl.scala:1217) at com.databricks.libraries.server.ManagedLibraryManagerImpl$ClusterStatus.installLibsWithResolution(ManagedLibraryManagerImpl.scala:719) at com.databricks.libraries.server.ManagedLibraryManagerImpl$ClusterStatus.installLibs(ManagedLibraryManagerImpl.scala:705) at com.databricks.libraries.server.ManagedLibraryManagerImpl$InstallLibTask$1.run(ManagedLibraryManagerImpl.scala:387) at com.databricks.threading.NamedExecutor$$anon$2.$anonfun$run$1(NamedExecutor.scala:356) at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:263) at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:261) at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:258) at com.databricks.threading.NamedExecutor.withAttributionContext(NamedExecutor.scala:285) at com.databricks.threading.NamedExecutor$$anon$2.run(NamedExecutor.scala:355) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**
Install through the maven installer on Databricks (either through search or as mentioned in the instructions)

**Expected behavior**
Install Correctly

**Info (please complete the following information):**
 - SynapseML Version: 0.9.3
 - Spark Version [e.g. 3.2]
 - Spark Platform [e.g. Databricks]

**Comment by zwag20** [comment]
Would it be possible to get the previous version back? That was working

**Comment by mhamilton723** [comment]
@zwag20 that version was unfortunately not released right. Try latest instructions for 0.9.4
