### ISSUE TITLE
Pre-built Docker container not working

### ISSUE THREAD

**Issue by yliu7366** [microsoft/SynapseML#1280]
**Describe the bug**
Followed the instruction to run the pre-built docker and tried to connect to http://locahost:8888 on the docker host machine but failed to connect. Also the documentation is missing so I could not find anything to help (https://github.com/microsoft/SynapseML/blob/master/docs/docker.md). Tested on a plain Ubuntu 20.04 installation.

**To Reproduce**
Simply run the docker command in the documentation and connect to localhost:8888 and it doesn't connect.

**Expected behavior**
I would expect to be able to connect to the notebooks as described

**Info (please complete the following information):**
 - SynapseML Version: [the latest pre-built docker]
 - Spark Version [the latest pre-built docker]
 - Spark Platform [the latest pre-built docker]

**Comment by mhamilton723** [comment]
@yliu7366 Thank you for bringing this to our attention we will investigate this discrepancy!

**Comment by memoryz** [comment]
Once the docker container instance is started, run `jupyter lab` from the `/notebooks` directory and open browser to http://127.0.0.1:8888/lab on the host and you will be able to play with the notebooks.
I just tested with mcr.microsoft.com/mmlspark/release:latest and it works.
