### ISSUE TITLE
Can this project be published to the Maven central repository

### ISSUE THREAD

**Issue by icankeep** [microsoft/SynapseML#1288]
Our container restricts the network. The internal maven repository can only synchronize with the maven central repository (https://mvnrepository.com/), and cannot be pulled from the azure repository (https://mmlspark.azureedge.net/maven), so I would like to ask, can it be published to the central repository? Or is there any other better solution?

**Comment by mhamilton723** [comment]
@icankeep Thanks for raising this. @serena-ruan is 95% of the way to achieving this. Hopefully version 0.9.5 will be on central

**Comment by serena-ruan** [comment]
That's right, we're pending on some library dependency issues, and will fix it soon! Version 0.9.5 will be published to maven central!

**Comment by icankeep** [comment]
Thanks, when will version 0.9.5 be released?

**Comment by serena-ruan** [comment]
Current ETA should be within 2 weeks

**Comment by icankeep** [comment]
Is there any progress please?

**Comment by serena-ruan** [comment]
Hi, sorry about the late reply. We've fixed the dependency issue, and will release 0.9.5 soon after upgrading to Spark3.2.

**Comment by mhamilton723** [comment]
0.9.5 is being released now which is on maven central :) Thanks for your patience!

**Comment by icankeep** [comment]
Is there a version that supports spark 3.0 (not 3.2) and is released in the central repository?
