### ISSUE TITLE
How to build SynapseML package for Databricks from the source code?

### ISSUE THREAD

**Issue by sinnfashen** [microsoft/SynapseML#1293]
Forgive me if it's a trivial question, this is the first time I use Scala and I'm not familiar with Java as well.

I'm trying to testing some [change](https://github.com/microsoft/SynapseML/pull/1292) in our own Databricks. But build with sbt package only provide a small jar where the one from maven contains multiple jars. I've also tried sbt assembly but even without any change and things are still broken. I saw error messages like can't find LGBM_NetWorkInit symbol. And I've run sbt setup before packaging.

**Comment by mhamilton723** [comment]
Thank you for this issue and your PR! To build locally with intellij you can check out these instructions:

https://microsoft.github.io/SynapseML/docs/reference/developer-readme/

To build on our server we will have to queue it for you for security reasons. Once a build runs we will post the man coordinates for the completed build which can be used to test on a cluster. SynapseML requires maven or another package manager to use and is not easily usable just as a standalone jar without sbt assembly

**Comment by mhamilton723** [comment]
Feel free to re-open if needed
