### ISSUE TITLE
What is the intent for having LightGBMClassificationModel, LightGBMClassifier? How are they different?

### ISSUE THREAD

**Issue by Nitinsiwach** [microsoft/SynapseML#1295]
The question is all there is actually. 
I am having to build the model using ```LightGBMClassifier``` but I cannot predict. For prediction I save as a native model then I use ```LightGBMClassificationModel```

I am struggling to understand the need for the two modules? Can you help me understand the idea behind the two modules?

**Comment by mhamilton723** [comment]
Good question! 

LightGBMClassifier trains a model and LightGBMClassificationModel is the model. The difference is that the former is a SparkML Estimator and the latter is a SparkML Transformer. 

See this for more info:
https://spark.apache.org/docs/latest/ml-pipeline.html#pipeline-components

Feel free to re-open if this doesn't answer your Q
