### ISSUE TITLE
mmlspark IsolationForest predictedLabel result column is always 0

### ISSUE THREAD

**Issue by sgar5067** [microsoft/SynapseML#1304]
**Describe the bug**
I've rewritten the Scala version of isolation_forest_example_usage.scala (https://gist.github.com/jverbus/610f16990a61b2b5c15e4ad861a5f2c2) into python and have run the notebook successfully. I'm using the same dataset used in the example and after the fit and transform, the outlierScore is present but the predictedLabel  is always 0. I've added additional rows which are sure to be anomalous but even these do not result in an anomaly.

SynapseML Reference can be found here: https://microsoft.github.io/SynapseML/docs/documentation/estimators/estimators_core/#isolationforest

**To Reproduce**
Dataset is attached...

from pyspark.sql import functions as f
from pyspark.sql.types import *

import scipy.io
import numpy as np
import pandas as pd

from synapse.ml.isolationforest import *
from pyspark.ml.feature import VectorAssembler

rawData = (spark.read
  .format("csv")
  .option("comment", "#")
  .option("header", "false")
  .option("inferSchema", "true")
  .load("dbfs:/FileStore/shuttle_trn.csv")
)

selectedCols = [
'features', 
'label'
]

#### rename column used for labels, remove rows with label equal 4 and set all rows with label equal 1 to 0 (inlier) and the balance of rows to 1 (outlier)
cols = rawData.columns
rawData = rawData.withColumnRenamed('_c9', 'label')
rawData = rawData.filter(f.col('label') != 4).withColumn('label', f.when(f.col('label') == 1, 0).otherwise(1))

#### Add BS data that should result in an Anomaly
vals = [(0,0,0,0,0,0,0,0,0,1)]
df = spark.createDataFrame(vals, rawData.columns)
rawData = rawData.union(df)
display(rawData.filter(f.col('_c0') == 0))

#### Encode
assembler = VectorAssembler(inputCols = cols[0:len(cols) - 1], outputCol= 'features')
data = (assembler.transform(rawData).select(selectedCols))

#### Fit and Transform
contamination = 0.1
isolationForest = (IsolationForest()
      .setFeaturesCol("features")
      .setContamination(contamination)
      .setContaminationError(0.01 * contamination)
      .setRandomSeed(1))

isolationForestModel = isolationForest.fit(data)
dataWithScores = isolationForestModel.transform(data)
display(dataWithScores)

**Expected behavior**
Anomalies identified via the IF model should be updated in the predictedLabel column.

**Info (please complete the following information):**
 - SynapseML Version: com.microsoft.azure:synapseml_2.12:0.9.4
 - Spark Version: 3.1.2
 - Spark Platform: Databricks 8.4

[shuttle.trn.csv](https://github.com/microsoft/SynapseML/files/7695732/shuttle.trn.csv)

**Comment by mhamilton723** [comment]
@eisber who added isolation forrest

**Comment by eisber** [comment]
can you try to set the setOutlierScoreThreshold to some value between 0 and 1? I think the outlierScoreThreshold defaults to -1 see here: https://github.com/linkedin/isolation-forest/blob/master/isolation-forest/src/main/scala/com/linkedin/relevance/isolationforest/IsolationForestModel.scala#L72

**Comment by sgar5067** [comment]
The setOutlierScoreThreshold is not available. That being said, I'm using the outlierScore to determine what I believe to be the optimal threshold and then updating predictedLabel to the calculated value based on the threshold. Other implementations I've used calculate the optimal value automatically based on the outlier scores.
![if_methods](https://user-images.githubusercontent.com/34171746/146601454-cf0e7a1f-3135-4671-a094-bd9336c01ebb.png)

**Comment by eisber** [comment]
@mhamilton723  do you know why the setOutlierScoreThreshold is private? https://github.com/linkedin/isolation-forest/blob/master/isolation-forest/src/main/scala/com/linkedin/relevance/isolationforest/IsolationForestModel.scala#L32

@sgar5067  I assume you already access the score through the scoreColumn, right? https://github.com/linkedin/isolation-forest/blob/master/isolation-forest/src/main/scala/com/linkedin/relevance/isolationforest/IsolationForestModel.scala#L71

@jverbus can you comment on automatically calculating the score? @sgar5067 how do you prioritize precision/recall?

**Comment by sgar5067** [comment]
Yes, outlierScore is returned in the transform results. I use these results to manually determine a threshold by creating a histogram of success and failure bucketing results by outlierScore as is seen in the graph attached. For this example I'd set predictedLabel myself to 1 for all rows in which outlierScore is greater then ~ 0.525...
![if_hist](https://user-images.githubusercontent.com/34171746/146816634-9f114e33-2f97-4fc4-a1e4-620e53ed9fa8.png)
.

**Comment by memoryz** [comment]
outlierScoreThreshold is automatically calculated by the estimator, that's probably why the inner model does not allow the threshold to be set by user. @jverbus can confirm whether this is by design.

The root cause of the bug is due to the wrapper model and the inner model not exchanging parameters properly.

**Comment by sgar5067** [comment]
Apologies, can you provide the method I need to use to access the changes?

**Comment by memoryz** [comment]
@sgar5067 simply reference `com.microsoft.azure:synapseml_2.12:0.9.4-41-9e51ba7d-SNAPSHOT` (or whatever the latest master version is) with resolver `https://mmlspark.azureedge.net/maven`.
You don't need to change your code. The outlierScoreThreshold is auto-computed in the estimator, and the model will compute the predicted label based on the outlierScoreThreshold.
