### ISSUE TITLE
Documentation for the booster object LightGBMClassificationModel.getLightGBMBooster() API

### ISSUE THREAD

**Issue by Nitinsiwach** [microsoft/SynapseML#1305]
**Is your feature request related to a problem? Please describe.**
There are functionalities that are not available via the LightGBMClassificationModel e.g ```predictLeaf```. There are other examples as well. These functionalities are useful in creating composite models. For example: Using the leaf prediction values from lgbm as features to another model. Currently, I can't find any visibility into how to use the booster objects that we get from ```model.getLightGBMBooster()```. Its docstrings require one to be somewhat comfortable with scala and even so it is not comprehensive.

**Describe the solution you'd like**
Documentation of the booster API that we get from ```model.getLightGBMBooster()```

**Comment by mhamilton723** [comment]
Thanks for reaching out @Nitinsiwach, the predictLeaf API is defined on the LightGBMBooster returned from getLightGBMBooster(). The API is primarily available in scala and takes in a vector and returns an array of predictions for each leaf from my understanding. 

@imatiach-msft for visibility into this request for scaladocs for these methods

**Comment by Nitinsiwach** [comment]
There is ```leafPredictionCol``` available whicle creating ```lightgbm.LightGBMClassificationModel()```
