### ISSUE TITLE
Missing results with TextAnalyze transformer when batching data

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/SynapseML#1307]
**Describe the bug**

**To Reproduce**
Submit a batch of 21-25 records via `TextAnalyze` (25 is the maximum batch size for the Analysis Job endpoint)

**Expected behavior**
The output column contains text analysis results for all of the input data in the batch

**Actual behavior**
The output column contains 20 results.

**Info (please complete the following information):**
 - SynapseML Version:  `main` 
 - Spark Version: 3.1
 - Spark Platform Azure Synapse Workspace

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Microsoft/SynapseML/blob/master/CODEOWNERS) for better visibility

**Additional context**
The Analysis Status endpoint returns paged responses with a default page size of 20 records: https://westus2.dev.cognitive.microsoft.com/docs/services/TextAnalytics-v3-1/operations/AnalyzeStatus

**Comment by mhamilton723** [comment]
Thanks for opening this! Ack
