### ISSUE TITLE
The link to CyberML notebook in README.md is broken

### ISSUE THREAD

**Issue by martin0258** [microsoft/SynapseML#1321]
**Describe the bug**
The link to CyberML notebook in README.md is broken.
Broken link: https://github.com/Microsoft/SynapseML/blob/master/notebooks/CyberML%20-%20Anomalous%20Access%20Detection.ipynb

**To Reproduce**
Click the link in README.md
<img width="841" alt="Screen Shot 2021-12-22 at 11 52 52 AM" src="https://user-images.githubusercontent.com/1118615/147033192-08776b45-9435-4693-a572-4cb8979787a9.png">
<img width="841" alt="Screen Shot 2021-12-22 at 11 53 01 AM" src="https://user-images.githubusercontent.com/1118615/147033205-9c287253-3e02-44ea-9c28-dcd0699d7e26.png">

**Expected behavior**
It should be fixed to: https://github.com/microsoft/SynapseML/blob/master/notebooks/features/other/CyberML%20-%20Anomalous%20Access%20Detection.ipynb

**Additional context**
master branch https://github.com/microsoft/SynapseML/commit/1bbcb7b96db87e742344a54b403ab442786e737a

**Comment by imatiach-msft** [comment]
Closing this issue as it seems to be fixed and the PR has been merged.
