### ISSUE TITLE
Spark K8S cluster mode "ModuleNotFoundError: No module named 'synapse'"

### ISSUE THREAD

**Issue by salvatore-cipolla** [microsoft/SynapseML#1328]
I'm trying to execute the Isolation Forest synapse ML algorithm in Spark cluster model on Kubernetes. No matter what I try I cannot get the import of synapse.ml to work (while it runs perfectly locally). 

Here the command that I'm using to launch the job:
```
  spark-submit \
      --master k8s://https://$(minikube ip):8443 \
      --deploy-mode cluster \
      --name spark-example \
      --conf spark.executor.instances=2 \
      --conf spark.kubernetes.container.image=cip-spark:1.0.0 \
      --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
      --conf spark.kubernetes.pyspark.pythonVersion=3 \
      --packages com.microsoft.azure:synapseml_2.12:0.9.4 \
      --conf spark.jars.repositories=https://mmlspark.azureedge.net/maven
```

It should run as in local mode, installing at execution time the necessary packages, but it's not working.

 - SynapseML Version: 0.9.4
 - Spark Version: 3.2.0
 - Spark Platform: spark using K8S, cluster mode

```
Traceback (most recent call last):
File "/src/test.py", line 27, in <module>
import synapse.ml
ModuleNotFoundError: No module named 'synapse'
```

**Comment by salvatore-cipolla** [comment]
> 

I'm only working on python, haven't tried in Scala. Anyway the dependencies are downloaded on the spark driver, but they do not seem to be present on the workers.

**Comment by mhamilton723** [comment]
https://stackoverflow.com/questions/66358133/spark-submit-to-kubernetes-packages-not-pulled-by-executors

This seems to be similiar to what you are encountering^

**Comment by salvatore-cipolla** [comment]
Thank you for the answer. This doesn't seems to be the problem we are encountering. We even tried to pass the required jars using hdfs like this:
```
spark-submit \
    --master k8s://https://HOST:PORT \
    --deploy-mode cluster \
    --name spark-example \
    --conf spark.executor.instances=2 \
    --conf spark.kubernetes.container.image=gitlab.alidalab.it:5000/alida/analytics/spark-analytics/isolation-forest-model-cm:1.0.9 \
    --conf spark.kubernetes.pyspark.pythonVersion=3 \
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
    --jars hdfs://alida-test-hdfs-namenode:8020/user/root/jars/jars/com.beust_jcommander-1.27.jar,hdfs://alida-test-hdfs-namenode:8020/user/root/jars/jars/com.chuusai_shapeless_2.12-2.3.2.jar... \
    local://test.py
```
The test.py file contains:
```
import pyspark
spark = pyspark.sql.SparkSession.builder.appName("MyApp") \
            .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.9.4") \
            .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
            .getOrCreate()
import synapse.ml
```

Do you have any other suggestions? Have you ever tried synapse with k8s in cluster mode?

**Comment by mhamilton723** [comment]
We had a helm chart for spark a while ago and that seemed to work fine (It's still in the repo too)

I think the next steps in debugging would be to understand the exact distribution of loaded code. For example does it load on the head and not the workers. If it doesn't load on any then you will want to check out the logs to see whether there is a problem with jar resolution (A good idea to do anyway). If it just loads on the head then the question becomes: "how is it failing on the workers?". In particular,  is it just the python that isn't loaded on the workers or is it both the python and the java. 

To find out whether the java is loaded you can use py4j to create a class from java directly. Doing this in a map partitions will check it on the workers. 

Also one final sanity check is to see if this is happening with other spark packages that contain scala and python code. If that is the case then there is something wrong with package resolution in your system.

**Comment by salvatore-cipolla** [comment]
For some reason using these two configurations:
```
.config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.9.4") \
.config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
```
works only in local mode, not cluster mode. Anyway I managed to solve the problem by installing synapseml==0.9.4 with pip and adding to the python code the list of all necessary jars :
```
.config("spark.jars", "/opt/spark/jars/com.beust_jcommander-1.27.jar,/opt/spark/jars/com.chuusai_shapeless_2.12-2.3.2.jar,/opt/spark/jars/com.github.vowpalwabbit_vw-jni-8.9.1.jar,/opt/spark/jars/com.jcraft_jsch-0.1.54.jar,/opt/spark/jars/com.linkedin.isolation-forest_isolation-forest_3.0.0_2.12-1.0.1.jar,/opt/spark/jars/com.microsoft.azure_synapseml_2.12-0.9.4.jar,/opt/spark/jars/com.microsoft.azure_synapseml-cognitive_2.12-0.9.4.jar,/opt/spark/jars/com.microsoft.azure_synapseml-core_2.12-0.9.4.jar,/opt/spark/jars/com.microsoft.azure_synapseml-deep-learning_2.12-0.9.4.jar,/opt/spark/jars/com.microsoft.azure_synapseml-lightgbm_2.12-0.9.4.jar,/opt/spark/jars/com.microsoft.azure_synapseml-opencv_2.12-0.9.4.jar,/opt/spark/jars/com.microsoft.azure_synapseml-vw_2.12-0.9.4.jar,/opt/spark/jars/com.microsoft.cntk_cntk-2.4.jar,/opt/spark/jars/com.microsoft.cognitiveservices.speech_client-sdk-1.14.0.jar,/opt/spark/jars/com.microsoft.ml.lightgbm_lightgbmlib-3.2.110.jar,/opt/spark/jars/com.microsoft.onnxruntime_onnxruntime_gpu-1.8.1.jar,/opt/spark/jars/commons-codec_commons-codec-1.10.jar,/opt/spark/jars/commons-logging_commons-logging-1.2.jar,/opt/spark/jars/io.spray_spray-json_2.12-1.3.2.jar,/opt/spark/jars/org.apache.httpcomponents_httpclient-4.5.6.jar,/opt/spark/jars/org.apache.httpcomponents_httpcore-4.4.10.jar,/opt/spark/jars/org.apache.httpcomponents_httpmime-4.5.6.jar,/opt/spark/jars/org.apache.spark_spark-avro_2.12-3.0.0.jar,/opt/spark/jars/org.beanshell_bsh-2.0b4.jar,/opt/spark/jars/org.openpnp_opencv-3.2.0-1.jar,/opt/spark/jars/org.scalactic_scalactic_2.12-3.0.5.jar,/opt/spark/jars/org.scala-lang_scala-reflect-2.12.4.jar,/opt/spark/jars/org.spark-project.spark_unused-1.0.0.jar,/opt/spark/jars/org.testng_testng-6.8.8.jar,/opt/spark/jars/org.typelevel_macro-compat_2.12-1.1.1.jar") \
```
I found that these jars must be in a certain folder, changing the folder might lead to problems. So I if somebody has a similar problem I suggest /opt/spark/jars location.

synapseml==0.9.4 python package was not necessary in local mode, however It was in cluster mode. 

Thanks for the help, I think the issue can be closed.

**Comment by mhamilton723** [comment]
Thanks for the postmortem @salvatore-cipolla!
