### ISSUE TITLE
How to choose feature_parallel distributed learning algorihtm?

### ISSUE THREAD

**Issue by Nitinsiwach** [microsoft/SynapseML#1340]
I can see [here](https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html) that the lightgbm can choose from three different distributed learning algorithms. One has to set ```tree_learner``` to one of ```data_parallel```, ```voting_parallel``` or ```feature_parallel```. 

Can you please guide me to the ```tree_learner``` parameter in the ```synapse.ml.lightgbm.LightGBMClassifier``` module. I can see a ```parallelism``` argument that it accepts but, that has only ```data_parallel``` and ```voting_parallel``` as the valid choice

**Comment by imatiach-msft** [comment]
@Nitinsiwach lightgbm in synapseml can support data_parallel and voting_parallel mode using the parallelism parameter:

https://github.com/microsoft/SynapseML/blob/master/lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/params/LightGBMParams.scala#L16

You can use this guide to decide whether to use data_parallel or voting_parallel:

![image](https://user-images.githubusercontent.com/24683184/149151066-05219993-a6ae-4749-b019-76a5c18eaff0.png)

Currently feature_parallel is not supported in this synapseml repository, but it could be added in the future.  When data is small you can always run it on single node anyway, but feature_parallel may speed up the training for small data.  It has very limited use, but it could be implemented.

Hope this helps!

**Comment by Nitinsiwach** [comment]
Thank you prompt reply :). This resolves my query
