### ISSUE TITLE
Getting the message No module named 'mmlspark.cyber'  in Azure Databricks

### ISSUE THREAD

**Issue by garybushey** [microsoft/SynapseML#1344]
**Describe the bug**
I added the mmlspark package using the Databricks instructions from https://mmlspark.blob.core.windows.net/website/index.html, leaving the repository field empty.    It loaded fine but when I try to run a playbook I get the error: No module named 'mmlspark.cyber'

Did I miss something?

**To Reproduce**
Load the package into an Azure Databricks and try the command "from mmlspark.cyber.dataset import DataFactory " from a Notebooks

**Info (please complete the following information):**
 - SynapseML Version: unknown
 - Spark Version 3.1.2
 - Spark Platform : Azure Databricks

** Stacktrace**
```
ModuleNotFoundError                       Traceback (most recent call last)
<command-797794001272818> in <module>
----> 1 from mmlspark.cyber.dataset import DataFactory
      2 from mmlspark.cyber.anomaly.collaborative_filtering import AccessAnomaly
      3 
      4 from pyspark.sql import functions as f, types as t
      5 import numpy as np

/databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py in import_patch(name, globals, locals, fromlist, level)
    156             # Import the desired module. If you’re seeing this while debugging a failed import,
    157             # look at preceding stack frames for relevant error information.
--> 158             original_result = python_builtin_import(name, globals, locals, fromlist, level)
    159 
    160             is_root_import = thread_local._nest_level == 1

ModuleNotFoundError: No module named 'mmlspark.cyber'
```

**Comment by memoryz** [comment]
Please refer to [the latest doc](https://microsoft.github.io/SynapseML/docs/features/other/CyberML%20-%20Anomalous%20Access%20Detection/):
```python
from synapse.ml.cyber.dataset import DataFactory
```

**Comment by mhamilton723** [comment]
Feel free to re-open if needed!
