### ISSUE TITLE
For contextualbandits the params are not clear.

### ISSUE THREAD

**Issue by musram** [microsoft/SynapseML#1351]
estimator = VowpalWabbitContextualBandit() \
    .setArgs("--cb_explore_adf --epsilon 0.2 --quiet") \
    .setParallelism(6) \
    .setSharedCol('hour_feature') \
    .setAdditionalSharedFeatures(['placementId_feature', 'countryId_feature','resolvedAdType_feature', 'isWifi_feature', 'deviceOsId_feature', 'deviceTypeId_feature' ]) \
    .setFeaturesCol('features') \
    .setUseBarrierExecutionMode(False)\
    .setChosenActionCol('chosenAction')\
    .setLabelCol('cost')\
    .setProbabilityCol('probability')

My questions are:
(a) My context features are ['hour_feature', 'placementId_feature', 'countryId_feature','resolvedAdType_feature', 'isWifi_feature', 'deviceOsId_feature', 'deviceTypeId_feature']. What setSharedCol and setAdditionalSharedFeatures means? Can you provide the link to the docs which explains it?
(b) How do you combine context features and action features? For example, in Vowpal wabbit we can have two spaces U for context and A for action. You can combine it using the command -qUA
(c) How do you generate the model in a human-readable form which can be done using -inv in vowpal wabbit.?

Thanks,
Sai

**Comment by mhamilton723** [comment]
@jackgerrits For viz

**Comment by eisber** [comment]
Standard SparkML puts all features into a single column (e.g. features) and expects either the ML algo or upstream components to perform feature crossing. Since VW has the capability to perform at-execution-time feature cross of high-dimensional features, the API was extend to allow for multiple Spark vectors (e.g. sparse or dense) to be passed into the ML algo. (FYI performing feature cross ahead of time as SparkML is designed to, can be computational and space infeasible).

wrt to setSharedCol: specifically for contextual bandit, VW space optimized on how data was passed in for the typical scenario rank multiple items for 1 user. From an ML perspective the algo needs the features for each item and the feature of the user. Internally VW predicts for each item taking both the user and item features into account. To avoid duplicating the user features for each item the concept of "shared" features was invented. The user features are appended for each item.
wrt to setAdditionalSharedFeatures: each VW namespace is represented by a single Spark column backed by a SparkML vector (dense or sparse). the method allows to map additional spark columns to VW shared namespaces.
wrt to combining ontextual and action features: following VW convention, the first letter of the namespace is used when specifying quadratic features (e.g. -qUA). The Spark column name is used as VW namespace (it seems you have h, p, c, r, i, d,d)
wrt to human-readable model: since the VW estimator operates on SparkML vector (dense/spark) the knowledge of the input data is lost. This is a trade-off to enable standard SparkML featurizers. You might be able to recover the hashing by using the VowpalWabbitFeaturizer and mapping it to the input - mapping these values to feature offsets and weights might be an additional adventure. @jackgerrits any ideas on your end?

**Comment by jackgerrits** [comment]
Yeah I think it would be an adventure for sure, but as you said the VowpalWabbitFeaturizer could potentially maintain a mapping which could be used to reconstruct the input from hashes. This sort of thing is always tricky because there are a number of components which are used to get the final feature/weight index.

**Comment by eisber** [comment]
the namespace names are "User" and "Action" so -q UA seems right (it's case-sensitive). user=Tom is a feature, not a namespace.
@jackgerrits  can you double check me?

**Comment by jackgerrits** [comment]
The default features (actions) col is `features` (https://mmlspark.blob.core.windows.net/docs/0.9.5/pyspark/synapse.ml.vw.html#synapse.ml.vw.VowpalWabbitRegressor.VowpalWabbitRegressor), which is empty right now.

If you update the featurizer to output to features for action features and if the column names correspond to namespaces wouldnt' the required interactions be: `-q ut -q ua -q ta`?

**Comment by musram** [comment]
Thanks, @jackgerrits @eisber.
"If you update the featurizer to output to features for action features and if the column names correspond to namespaces wouldnt' the required interactions be: -q ut -q ua -q ta?"

Yes, this is correct.

This is my understanding. Pls, correct me if I am wrong.

(a) There is no concept of Space as in VW. We have to pass the combinations eg -q ut etc.
(b) As mentioned in https://microsoft.github.io/SynapseML/docs/features/vw/Vowpal%20Wabbit%20-%20Overview/, the support is there for --bag, --cover, and --softmax.
(c) It seems like the current support is for only ips and not for other cb_types like dr, dm, and mtr.
(4) The weightCol  param in https://mmlspark.blob.core.windows.net/docs/0.9.5/pyspark/synapse.ml.vw.html#synapse.ml.vw.VowpalWabbitRegressor.VowpalWabbitRegressor.      corresponds to the weight of the data point. As this feature was not there for VW contextual bandit, the workaround was to divide the prob by weight as discussed in https://github.com/VowpalWabbit/vowpal_wabbit/issues/3472. I think this is resolved in the SynapseML support of contextual bandit.
(5) I will explore VowpalWabbitFeaturizer as mentioned by @jackgerrits and let you know the results.

**Comment by musram** [comment]
Hai @jackgerrits 
I have one more additional question. I am trying to build at least one workable model which I was able to build using VW.
My code is:
pipeline = Pipeline(stages=[
  VowpalWabbitFeaturizer(inputCols=['hour'], outputCol='hour_feature'),
  VowpalWabbitFeaturizer(inputCols=['placementId'], outputCol='placementId_feature'),
  VowpalWabbitFeaturizer(inputCols=['isAudienceBiddingPlacement'], outputCol='isAudienceBiddingPlacement_feature'),
  VowpalWabbitFeaturizer(inputCols=['chosenAction'], outputCol='chosenAction_feature'),
  
  VectorZipper(inputCols=['chosenAction_feature' ], outputCol='features')
])

estimator = VowpalWabbitContextualBandit() \
    .setArgs("--cb_explore_adf --epsilon 0.2 --quiet --l2 10 --learning_rate 0.5" ) \
    .setParallelism(6) \
    .setSharedCol('hour_feature') \
    .setAdditionalSharedFeatures(['placementId_feature', 'isAudienceBiddingPlacement_feature']) \
    .setFeaturesCol('features') \
    .setUseBarrierExecutionMode(False)\
    .setChosenActionCol('chosenAction')\
    .setLabelCol('cost')\
    .setProbabilityCol('probability')

I have one action column. 


I am getting this error:
22/01/22 16:47:16 INFO CoarseGrainedExecutorBackend: Got assigned task 909
22/01/22 16:47:16 INFO Executor: Running task 1.1 in stage 41.0 (TID 909)
22/01/22 16:47:16 WARN VowpalWabbitContextualBandit: VowpalWabbit args: --cb_explore_adf --epsilon 0.2 --quiet --l2 10 --learning_rate 0.5 --holdout_off --span_server 10.139.64.4 --span_server_port 44611 --unique_id 1603056462 --total 4  --node 1 --no_stdin
22/01/22 16:47:16 WARN VowpalWabbitContextualBandit: Casting column 'cost' to float. Loss of precision.
22/01/22 16:47:16 WARN VowpalWabbitContextualBandit: Casting column 'probability' to float. Loss of precision.
22/01/22 16:47:16 INFO FilterCompat: Filtering using predicate: and(noteq(ecpmFloor, null), noteq(revenue, null))
22/01/22 16:47:17 WARN VowpalWabbitContextualBandit: Casting column 'cost' to float. Loss of precision.
22/01/22 16:47:17 WARN VowpalWabbitContextualBandit: Casting column 'probability' to float. Loss of precision.
22/01/22 16:47:17 WARN VowpalWabbitContextualBandit: Casting column 'cost' to float. Loss of precision.
22/01/22 16:47:17 WARN VowpalWabbitContextualBandit: Casting column 'probability' to float. Loss of precision.
22/01/22 16:47:17 WARN VowpalWabbitContextualBandit: Casting column 'cost' to float. Loss of precision.
22/01/22 16:47:17 WARN VowpalWabbitContextualBandit: Casting column 'probability' to float. Loss of precision.
22/01/22 16:47:18 WARN VowpalWabbitContextualBandit: Casting column 'cost' to float. Loss of precision.
22/01/22 16:47:18 WARN VowpalWabbitContextualBandit: Casting column 'probability' to float. Loss of precision.
22/01/22 16:47:18 INFO FileScanRDD: Reading File path: dbfs:/mnt/blobglobal/batchstore/secure/projects/data/dynamiy/2022-01-15-01/part-00000-581d5b70-14b4-4618-b892-7758d894d280-c000.snappy.parquet, range: 134217728-268435456, partition values: [empty row], modificationTime: 1642237016000.
22/01/22 16:47:18 ERROR Executor: Exception in task 1.1 in stage 41.0 (TID 909)
java.lang.Exception: VW failed with args: --cb_explore_adf --epsilon 0.2 --quiet --l2 10 --learning_rate 0.5 --holdout_off --span_server 10.139.64.4 --span_server_port 44611 --unique_id 1603056462 --total 4  --node 1 --no_stdin
	at com.microsoft.azure.synapse.ml.vw.VowpalWabbitBase.$anonfun$trainInternal$1(VowpalWabbitBase.scala:406)
	at com.microsoft.azure.synapse.ml.core.utils.FaultToleranceUtils$.retryWithTimeout(FaultToleranceUtils.scala:24)
	at com.microsoft.azure.synapse.ml.core.utils.FaultToleranceUtils$.retryWithTimeout(FaultToleranceUtils.scala:29)
	at com.microsoft.azure.synapse.ml.core.utils.FaultToleranceUtils$.retryWithTimeout(FaultToleranceUtils.scala:29)
	at com.microsoft.azure.synapse.ml.core.utils.FaultToleranceUtils$.retryWithTimeout(FaultToleranceUtils.scala:29)
	at com.microsoft.azure.synapse.ml.core.utils.FaultToleranceUtils$.retryWithTimeout(FaultToleranceUtils.scala:29)
	at com.microsoft.azure.synapse.ml.vw.VowpalWabbitBase.trainIteration$1(VowpalWabbitBase.scala:346)
	at com.microsoft.azure.synapse.ml.vw.VowpalWabbitBase.$anonfun$trainInternal$7(VowpalWabbitBase.scala:421)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:228)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:903)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:903)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:380)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:344)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:380)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:344)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:153)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:122)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:93)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:824)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1621)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:827)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:683)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.microsoft.azure.synapse.ml.vw.VowpalWabbitContextualBandit.$anonfun$trainRow$2(VowpalWabbitContextualBandit.scala:243)
	at com.microsoft.azure.synapse.ml.vw.VowpalWabbitContextualBandit.$anonfun$trainRow$2$adapted(VowpalWabbitContextualBandit.scala:232)
	at com.microsoft.azure.synapse.ml.vw.VowpalWabbitUtil$.prepareMultilineExample(VowpalWabbitUtil.scala:87)
	at com.microsoft.azure.synapse.ml.vw.VowpalWabbitContextualBandit.$anonfun$trainRow$1(VowpalWabbitContextualBandit.scala:232)
	at com.microsoft.azure.synapse.ml.vw.VowpalWabbitContextualBandit.$anonfun$trainRow$1$adapted(VowpalWabbitContextualBandit.scala:230)
	at s

**Comment by musram** [comment]
@jackgerrits  I took an example from the  test case from your repository and modified it as :
def get_data_two_shared():
        # create sample data
        schema = StructType([
            StructField("shared_text", StringType()),
            StructField("shared_text2", StringType()),
            StructField("action1", IntegerType()),
            StructField("chosenAction", IntegerType()),
            StructField("label", DoubleType()),
            StructField("probability", DoubleType())
        ])

        data = spark.createDataFrame([
            ("shared_f", "shared_f2", 1,  1, 1.0, 0.8),
            ("shared_f", "shared_f2", 2,  2, 1.0, 0.8),
            ("shared_f", "shared_f2", 2,  2, 4.0, 0.8),
            ("shared_f", "shared_f2", 1,  1, 1.0, 0.8),
            ("shared_f", "shared_f2", 2,  2, 1.0, 0.8),
            ("shared_f", "shared_f2", 1,  1, 1.0, 0.8),
            ("shared_f", "shared_f2", 2,  2, 1.0, 0.8),
            ("shared_f", "shared_f2", 2,  2, 4.0, 0.8),
            ("shared_f", "shared_f2", 1,  1, 1.0, 0.8),
            ("shared_f", "shared_f2", 2,  2, 1.0, 0.8),
            ("shared_f", "shared_f2", 11,  1, 0.0, 0.8)], schema) \
            .coalesce(1)

        # featurize data
        shared_featurizer = VowpalWabbitFeaturizer(inputCols=['shared_text'],
                                                   outputCol='shared')
        shared_featurizer2 = VowpalWabbitFeaturizer(inputCols=['shared_text2'],
                                                    outputCol='shared2')
        action_one_featurizer = VowpalWabbitFeaturizer(
            inputCols=['action1'], outputCol='action1_features')
        action_merger = VectorZipper(
            inputCols=['action1_features'],
            outputCol='features')
        pipeline = Pipeline(stages=[
            shared_featurizer, shared_featurizer2, action_one_featurizer,
             action_merger
        ])
        tranformation_pipeline = pipeline.fit(data)
        return tranformation_pipeline.transform(data)

featurized_data = get_data_two_shared()
estimator1 = VowpalWabbitContextualBandit() \
    .setArgs("--cb_explore_adf --epsilon 0.2 --quiet") \
    .setSharedCol('shared')\
    .setAdditionalSharedFeatures(["shared2"]) \
    .setUseBarrierExecutionMode(False)
model1 = estimator1.fit(featurized_data)

I am not getting errors if the number of rows in data is less than 8. But more than 8 gives me the error is same as I shared in the previous chat.

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 79.0 failed 4 times, most recent failure: Lost task 0.3 in stage 79.0 (TID 2316) (10.139.64.9 executor 2): java.lang.Exception: VW failed with args: --cb_explore_adf --epsilon 0.2 --quiet  --no_stdin
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-863465987605118> in <module>
      5     .setAdditionalSharedFeatures(["shared2"]) \
      6     .setUseBarrierExecutionMode(False)
----> 7 model1 = estimator1.fit(featurized_data)

/databricks/python_shell/dbruntime/MLWorkloadsInstrumentation/_pyspark.py in patched_method(self, *args, **kwargs)
     28             call_succeeded = False
     29             try:
---> 30                 result = original_method(self, *args, **kwargs)
     31                 call_succeeded = True
     32                 return result

/databricks/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
    159                 return self.copy(params)._fit(dataset)
    160             else:
--> 161                 return self._fit(dataset)
    162         else:
    163             raise TypeError("Params must be either a param map or a list/tuple of param maps, "

**Comment by musram** [comment]
Hi, @jackgerrits and @eisber. Can you suggest any fix the above problems?

**Comment by eisber** [comment]
@musram  Jack and I are setting up a debugging env to repro the problem.

**Comment by musram** [comment]
@eisber  and @jackgerrits, we were able to look at your source code and were able to pass the data as required by your framework.  We are not getting the above error.

But there is one issue we are facing when we pass chosenAction = 0 because of  
   val selectedActionIdx = row.getInt(chosenActionColIdx)
          if (selectedActionIdx == 0) {
            throw new IllegalArgumentException("Chosen action index is 1 based - cannot be 0")
          }

https://github.com/microsoft/SynapseML/blob/865d189496f4958e07ca3178155063ddd3b908d0/vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitContextualBandit.scala#L235

Is there any constraint that you restrict the chosenAction to take value >= 1? 

Sai

**Comment by eisber** [comment]
The index is simply 1 to n vs 0 to n-1. you are still able to select all actions.

**Comment by musram** [comment]
@eisber, yes I understand. We have to make a simple change in our data. 
Thanks. I will close this issue.
