### ISSUE TITLE
add a version to the pyspark package

### ISSUE THREAD

**Issue by imatiach-msft** [microsoft/SynapseML#1353]
we should add a version to the pyspark package, currently there is no version field

import mmlspark
mmlspark.__version__

it does not exist :(

**Comment by mhamilton723** [comment]
Should be something like 

synapse.ml.core.__version__

Also mmlspark namespace is deprecated and just reroutes to synapse.ml namespace. The fact that its in the core namespace is because the new setup is a namespace package which allows us to modularly install diff components.
