### ISSUE TITLE
Documentation for ComputeModelStatistics

### ISSUE THREAD

**Issue by Nitinsiwach** [microsoft/SynapseML#1360]
**Is your feature request related to a problem? Please describe.**
One day someone will definitely end up losing his/her sanity because ```cms.transform``` needs the ```scoredLabelsCol``` columns to be only in ```DoubleType```.  Since, this is a labels column one would expect this to be ```IntegerType```. If they ventured to try ```FloatType``` it would still give and error. It needs ```DoubleType``` and the error message ```java.lang.Exception: Error: prediction and label columns invalid or missing``` is not very helpful. 

**Describe the solution you'd like**
Informative docstring for ```ComputeModelStatistics```

Also, thank you guys, for this wonderful wonderful package :)

**Comment by memoryz** [comment]
The PR will auto convert Int/Float types to DoubleType.

**Comment by Lucca-mito** [comment]
> One day someone will definitely end up losing his/her sanity

That someone was me; issue is still present as of `1.0.5-spark3.5`. (That said, the workaround is as simple as `.cast(DoubleType())`.)
