### ISSUE TITLE
library Install issue on Synapse

### ISSUE THREAD

**Issue by mengdl** [microsoft/SynapseML#1370]
**Describe the bug**
The doc in here(https://github.com/Microsoft/SynapseML#apache-livy-and-hdinsight) is not correct for Synapse, as Azure Synapse only has Spark pool 3.1 or 2.4 so far(2022/01/27), it does not work for 0.9.5. 

According to https://microsoft.github.io/SynapseML/, the user should install com.microsoft.azure:synapseml_2.12:0.9.4 on Spark 3.1 pool. 

**Info (please complete the following information):**
 - SynapseML Version: 0.9.5
 - Spark Version: Spark 3.1
 - Spark Platform: Azure Synapse Spark

**Comment by memoryz** [comment]
@serena-ruan what's the plan here?

**Comment by imatiach-msft** [comment]
@mengdl @serena-ruan @memoryz I made a minor doc update to the readme to resolve this:
https://github.com/microsoft/SynapseML/pull/1372

**Comment by imatiach-msft** [comment]
closing issue as PR has been merged:
https://github.com/microsoft/SynapseML/pull/1372#event-5982319928
