### ISSUE TITLE
MLFlow Integration

### ISSUE THREAD

**Issue by hoemblem** [microsoft/SynapseML#1407]
**Is your feature request related to a problem? Please describe.**
Being able to utilise Mlflow (https://docs.microsoft.com/en-gb/azure/databricks/applications/mlflow/quick-start) in Databricks when using SynapseML would be helpful for storing models and metrics. I did see this feat: https://github.com/microsoft/SynapseML/pull/1277/files but wasn't sure if there is any documentation on using Mlflow with SynapseML?

**Describe the solution you'd like**
Documentation or examples of integrating mlflow with SynapseML

**Comment by mhamilton723** [comment]
Thanks for raising this @hoemblem, adding the MLFlow lead @serena-ruan  for her comments

**Comment by serena-ruan** [comment]
Thanks! Will update our website with some MLFlow examples.

**Comment by hoemblem** [comment]
That's awesome - thank you!

**Comment by mhamilton723** [comment]
https://microsoft.github.io/SynapseML/docs/next/mlflow/examples/

For others looking for examples they have just been published here!
