### ISSUE TITLE
Doubts regarding the contextual bandit

### ISSUE THREAD

**Issue by musram** [microsoft/SynapseML#1431]
We are  using  VW with  map reduced framework. Now we want to move to the databricks  framework. I have few doubts. 
Let us take the example from synapseML test case
schema = StructType([
            StructField("shared_text", StringType()),
            StructField("action1", StringType()),
            StructField("action2_feat1", StringType()),
            StructField("action2_feat2", StringType()),
            StructField("chosenAction", IntegerType()),
            StructField("label", DoubleType()),
            StructField("probability", DoubleType())
        ])

        data = spark.createDataFrame([
            ("shared_f", "action1_f", "action2_f", "action2_f2=0", 1, 1.0, 0.8),
            ("shared_f", "action1_f", "action2_f", "action2_f2=1", 2, 1.0, 0.8),
            ("shared_f", "action1_f", "action2_f", "action2_f2=1", 2, 4.0, 0.8),
            ("shared_f", "action1_f", "action2_f", "action2_f2=0", 1, 0.0, 0.8)], schema)\
            .coalesce(1)

        # featurize data
        shared_featurizer = VowpalWabbitFeaturizer(inputCols=['shared_text'],
                                                   outputCol='shared')
        action_one_featurizer = VowpalWabbitFeaturizer(
            inputCols=['action1'], outputCol='action1_features')
        action_two_featurizer = VowpalWabbitFeaturizer(
            inputCols=['action2_feat1', 'action2_feat2'],
            outputCol='action2_features')
        action_merger = VectorZipper(
            inputCols=['action1_features', 'action2_features'],
            outputCol='features')
        pipeline = Pipeline(stages=[
            shared_featurizer, action_one_featurizer, action_two_featurizer,
            action_merger
        ])

Q1: Not clear about the chosenAction. It looks like the index in action_merger.
Q2: We are using --cb_explore_adf because our bandit's arms are varying but I have only one feature for action. How to extend the chosenAction for this one feature. So if my action feature has value like action=1, action=2, action=3... Then what will be my chosenAction?
Q3. can we pass --predictions in the arg to get the prediction prob for all the arms?

@eisber @jackgerrits

**Comment by eisber** [comment]
Q1: not sure what action_merger is? chosenAction indexes the actionFeature array (see Q2)
Q2: maybe that's the biggest confusion here. the actionFeature column is [expected to be of type Array of Vector](https://github.com/microsoft/SynapseML/blob/master/vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitContextualBandit.scala#L172). The size of the array can vary with each row, thus the number of arms/actions can be different for every collected sample.
Q3: I believe the [distribution over all actions](https://github.com/microsoft/SynapseML/blob/master/vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitContextualBandit.scala#L348) is returned. From what I can see the [probabilities in order of action index are returned straight back](https://github.com/microsoft/SynapseML/blob/master/vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitContextualBandit.scala#L362). @jackgerrits ?

**Comment by musram** [comment]
@eisber  
As could not understand the relation between the action features and chosenAction clearly let us take the below example.
One sample data point from the data set which  is taken from (https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/test/train-sets/cb_load.dat)  is 

shared |User user=Tom time_of_day=morning
|Action article=politics 
|Action article=sports 
0:0.0:0.14285714498588012 |Action article=finance 
|Action article=health 


From your reply on Q2 I understand that you have to map each data point to the above format and pass it to the VW(https://github.com/microsoft/SynapseML/blob/58dd01fa7b17cbbfb7a53bc24ff508b2acd6d14c/vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitContextualBandit.scala#L249). 
 
The one data point according to the example will be  
column name : User  time_of_day  1action             2action              3action           4action      chosenAction
data point :      Tom   morning        article=politics  article=sports  article=finance  article=health   3

if I need to take the quadratic features it means I will take -q U1 -q U2 for (user * 1action, user* 2action)
If my understanding is not correct, Pls, explain using the above example.

**Comment by eisber** [comment]
action1, 2, 3, ... 4 are not individual columns, but there is a single "actions" column hold an array of Spark vectors.

As in the original example, the actions usually share the same namespaces. (e.g. Action). thus you can just do "-q UA" which forms quadratic features between |User and |Action.

**Comment by musram** [comment]
@eisber 

I am clear with your reply. 
"action1, 2, 3, ... 4 are not individual columns, but there is a single "actions" column hold an array of Spark vectors."  Is chosenAction a index in this vector pointing to that action taken?

**Comment by eisber** [comment]
@musram  correct, the choseAction indexes into the vector, indentifying the chosen action. @jackgerrits choseAction is still 1-based, right? while spark vectors are 0-based.

**Comment by musram** [comment]
Thanks @eisber  and @jackgerrits

**Comment by musram** [comment]
@jackgerrits  and @eisber 
https://github.com/microsoft/SynapseML/blob/58dd01fa7b17cbbfb7a53bc24ff508b2acd6d14c/vw/src/main/scala/com/microsoft/azure/synapse/ml/vw/VowpalWabbitContextualBandit.scala#L352.  In this line I think tuple (action_index, probability) should be saved. Otherwise we don't have the action to probability mapping as that information is lost by sorting.

When I do model.transfom(tranformed_data) I get 

 ....
 action_0_feature                   | (1073741824,[77534544],[1.0])                                                                                                                                                                                                                                                                                                   
 action_1_feature                   | (1073741824,[303227434],[1.0])                                                                                                                                                                                                                                                                                                  
 action_2_feature                   | (1073741824,[583928751],[1.0])                                                                                                                                                                                                                                                                                                  
 action_3_feature                   | (1073741824,[228090762],[1.0])                                                                                                                                                                                                                                                                                                  
 action_4_feature                   | (1073741824,[590293146],[1.0])                                                                                                                                                                                                                                                                                                  
 action_5_feature                   | (1073741824,[524137948],[1.0])                                                                                                                                                                                                                                                                                                  
 action_6_feature                   | (1073741824,[656072433],[1.0])                                                                                                                                                                                                                                                                                                  
 action_7_feature                   | (1073741824,[589576980],[1.0])                                                                                                                                                                                                                                                                                                  
 action_8_feature                   | (1073741824,[613053650],[1.0])                                                                                                                                                                                                                                                                                                  
 action_9_feature                   | (1073741824,[699207628],[1.0])                                                                                                                                                                                                                                                                                                  
 features                           | [(1073741824,[77534544],[1.0]), (1073741824,[303227434],[1.0]), (1073741824,[583928751],[1.0]), (1073741824,[228090762],[1.0]), (1073741824,[590293146],[1.0]), (1073741824,[524137948],[1.0]), (1073741824,[656072433],[1.0]), (1073741824,[589576980],[1.0]), (1073741824,[613053650],[1.0]), (1073741824,[699207628],[1.0])] 
 prediction                         | [0.9549999833106995, 0.004999999888241291, 0.004999999888241291, 0.004999999888241291, 0.004999999888241291, 0.004999999888241291, 0.004999999888241291, 0.004999999888241291, 0.004999999888241291, 0.004999999888241291] 

So the prediction column should be a List of tuple of action and probability.

**Comment by eisber** [comment]
since the probs are sorted by actionIndex you can infer the (action_index) from the position of the probability in the array
