### ISSUE TITLE
Broken Link - ICETransformer Example

### ISSUE THREAD

**Issue by JosephTLucas** [microsoft/SynapseML#1433]
**Describe the bug**
In [these release notes](https://github.com/microsoft/SynapseML/releases/tag/v0.9.5), you have this statement: "Learn about how to use the ICETransformer through [an example with the Adult Census dataset](https://microsoft.github.io/SynapseML/docs/next/features/responsible_ai/Interpretability%20-%20ICE%20explainer/)". I get a "Page not Found" from that link. I also don't see an ICE Explainer when I manually navigate to the Interpretability section of the docs.

**To Reproduce**
Click the link in the release notes

**Expected behavior**
The link should take users to some example page.

**Info (please complete the following information):**
N/A

** Stacktrace**
N/A

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Microsoft/SynapseML/blob/master/CODEOWNERS) for better visibility

**Additional context**
N/A

**Comment by mhamilton723** [comment]
Thank you its here and updating the release notes:

https://microsoft.github.io/SynapseML/docs/next/features/responsible_ai/Interpretability%20-%20PDP%20and%20ICE%20explainer/
