### ISSUE TITLE
Getting JAR files to run MMLSpark

### ISSUE THREAD

**Issue by sagargoyal96** [microsoft/SynapseML#1438]
I need MMLSpark that runs on Spark 2.4 on HDI for my project as that is the supported version. I only see a release candidate (rc) for that. Is there a proper release that works with Spark 2.4 ?
Also in our setup we need to add the JAR file for any Spark dependencies that we want installed on the HDI cluster. What is the way to download a JAR (or multiple JAR's) that can be added to the spark context and it will work. 
[Note] This is not for a Jupyter notebook on HDI, but jobs being run from artifacts which require the actual JAR already downloaded and present

**Comment by mhamilton723** [comment]
https://github.com/microsoft/SynapseML/tree/v1.0.0-rc4

This is the last release we had on Spark 2.4. You can use the specified maven coordinates or use sbt assembly to make an uber jar. Hope this helps!
