### ISSUE TITLE
Performance of keyphrase extraction on huge dataset

### ISSUE THREAD

**Issue by divya-r-kamat** [microsoft/SynapseML#1491]
I am using cognitive service from mmlspark package to extract keyphrases, I have dataset with ~500k (5 lakh records), its taking too long (job runs for more than 24 hrs) to extract keyphrases, is there any faster or efficient way to extract key phrases for huge dataset.

```
 keyphrase = (KeyPhraseExtractor()
     .setTextCol("text")
     .setLocation("eastus")
     .setSubscriptionKey(service_key)
     .setOutputCol("keyphrase")
     )
    
 results = keyphrase.transform(df_cleaned)
```

I am running the job on Synapse notebook on spark cluster.

Thanks,
Divya

AB#1761861

**Comment by mhamilton723** [comment]
Hey @divya-r-kamat yes there are some ways to improve perf

1 The most important way is batching: See here for some usage of the minibatch transformer
https://github.com/microsoft/SynapseML/blob/b25feab93a1c9e5ed879a5fcf9b1bfb9dfcbea55/cognitive/src/test/scala/com/microsoft/azure/synapse/ml/cognitive/split1/TextAnalyticsSuite.scala#L63

2. The next thing to check is whether you are getting throttled by cog services. You can check this in the portal. If so, consider making multiple services and parallelizing over them with the `.setSubscriptionKeyCol`

3. Another sanity check is partitioning. Make sure you have enough partitions of your dataframe to ensure even parallelism. I would suggest something like 100

4. Finally if you arent being throttled and you need more throughput, use the `.setConcurrency` setter to add some async parallelism. Hope this helps!
