### ISSUE TITLE
Request to add certain training parameters present in classic Lightgbm to Synapse ML

### ISSUE THREAD

**Issue by alzio2607** [microsoft/SynapseML#1514]
**Is your feature request related to a problem? Please describe.**
Some features present in the classic (non-spark) Lightgbm are not there in synapseML. These features are really needed for someone looking to switch from the classic way to Synapse .  It'll be appreciated if the parameters are integrated since they help with more precise training too.

**Describe the solution you'd like**
Would like to request the addition of the following params
cat_l2
max_cat_threshold
cat_smooth
min_data_per_group
min_data_in_bin

**Additional context**
Found 2 open issues pertaining to similar kind of request. Mentioning them here too. Creating this new issue for latest update
#997 
#789 

AB#1799267

**Comment by imatiach-msft** [comment]
@alzio2607 I think this is somewhat resolved with PR:
https://github.com/microsoft/SynapseML/pull/1444
which was merged recently, since
```
Add ability for LightBGM user to set custom args that aren't defined explicitly by SynapseML (as Vowpal Wabbit does now)
```
adding @svotaw 
Ofcourse, we should add these parameters to the API directly as well, in addition to the custom args parameter.

**Comment by svotaw** [comment]
You should be able to set those as well as any other manual parameter after the above changes.
