### ISSUE TITLE
Problem with reverse geocoding using SynapseML in Synapse Spark Pools

### ISSUE THREAD

**Issue by alidavoudian** [microsoft/SynapseML#1547]
**Describe the bug**
Reverse geocoding of some already generated coordinates of address returns "undefined"!

**To Reproduce**
Steps to reproduce the behavior, code snippets encouraged

# Create a dataframe that's tied to it's column names
df = spark.createDataFrame(((
    (45.32202, -75.83875),
    (47.62039, -122.34928),
    (45.37032, -75.70161),
    (45.3702793, -75.7037331),
    (45.28471, -75.73897),
    (48.85607, 2.29833)
  )), StructType([StructField("lat", DoubleType()), StructField("lon", DoubleType())]))

# Run the Azure Maps geocoder to enhance the data with location data
rev_geocoder = (ReverseAddressGeocoder()
    .setSubscriptionKey(azureMapsKey)
    .setLatitudeCol("lat")
    .setLongitudeCol("lon")
    .setOutputCol("output"))

# Show the results of your text query in a table format
display(rev_geocoder.transform(FixedMiniBatchTransformer().setBatchSize(10).transform(df)).select(col("*"),
      col("output.response.addresses").getItem(0).getField("address").getField("freeformAddress").alias("freeformAddress"),
      col("output.response.addresses").getItem(0).getField("address").getField("country").alias("country")
    ).drop("output"))

**Expected behavior**
We expect to see all the relevant addresses.

**Info (please complete the following information):**
 - SynapseML Version: 0.0.5
 - Spark Version: 3.1
 - Spark Platform: Synapse
 - You can find below the Spark session configuration:
%%configure -f
 {
   "name": "synapseml",
   "conf": {
       "spark.jars.packages": "com.microsoft.azure:synapseml_2.12:0.9.5-13-d1b51517-SNAPSHOT",
       "spark.jars.repositories": "https://mmlspark.azureedge.net/maven",
       "spark.jars.excludes": "org.scala-lang:scala-reflect,org.apache.spark:spark-tags_2.12,org.scalactic:scalactic_2.12,org.scalatest:scalatest_2.12",
       "spark.yarn.user.classpath.first": "true"
   }
 }

** Stacktrace**
```
Please post the stacktrace here if applicable
```

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Microsoft/SynapseML/blob/master/CODEOWNERS) for better visibility

**Additional context**

AB#1847442

**Comment by serena-ruan** [comment]
What is your output? Do you mean you're expecting the freeformAddress and country not containing empty values at all? The output.response.addresses should be the result directly returned by the cog service.

**Comment by ppruthi** [comment]
@serena-ruan  --- can you help classify what focus area is this issue under? Also could you apply the relevant label to the issue ?

**Comment by serena-ruan** [comment]
I think we can close this issue as we have internally discussed and solved the customer's problem 😃
