### ISSUE TITLE
SynapseML v0.9.5 does not work over Synapse Spark Poolv3.1 for the Azure Form Recognizer

### ISSUE THREAD

**Issue by alidavoudian** [microsoft/SynapseML#1548]
**Describe the bug**
The following code returns an empty list: (Note that when using the REST API to connect to the Form Recognizer, the result is not empty)
emptyDf = spark.createDataFrame([("",)])

listCustomModels = (ListCustomModels()
                  .setLinkedService(cognitive_service_name)
                  .setOp("full")
                  .setOutputCol("models")
                  .setConcurrency(5))

(listCustomModels
       .transform(emptyDf)
       .withColumn("modelIds", col("models.modelList.modelId"))
       .select("modelIds")).show()

**To Reproduce**

https://docs.microsoft.com/en-us/azure/synapse-analytics/machine-learning/tutorial-form-recognizer-use-mmlspark

**Expected behavior**

**Info (please complete the following information):**
 - SynapseML Version: 0.9.5
 - Spark Version: 3.1
 - Spark Platform: Azure Synapse

** Stacktrace**
```
Please post the stacktrace here if applicable
```

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Microsoft/SynapseML/blob/master/CODEOWNERS) for better visibility

**Additional context**

**Comment by serena-ruan** [comment]
Could you try replacing `.setLinkedService(cognitive_service_name)` with `.setLocation("YOUR_COG_SRV_LOCATION").setSubscriptionKey("YOUR_SUB_KEY")` to see if it works?
Chances are there're problems with the linked service.

**Comment by serena-ruan** [comment]
BTW, 0.9.5 is for Spark 3.2. If you're using Spark3.1 pool, please use 0.9.5-13-d1b51517-SNAPSHOT. You can refer to the installation part on this website https://microsoft.github.io/SynapseML/

**Comment by alidavoudian** [comment]
We really apprecitae if you schedule a meeting with us in Canada Revenue Agency, as we are stuck in two points with SynapaeML 1) connecting to Azure Form Recognizer and 2) connecting to Azure Maps

Kind regards, Cloud Database Services, Canada Revenue Agency

**Comment by serena-ruan** [comment]
I'll reach out to the team and schedule a meeting. In the meantime, could you double check your subscription key and location is correct? And could you double check the result of calling `listCustomModels.transform(emptyDf)` directly to see if it's also empty?

**Comment by NelGson** [comment]
@alidavoudian please send an email to negust@microsoft.com so that we can arrange a call

**Comment by alidavoudian** [comment]
1) I sent the request to negust@microsoft.com
2) I did check they subscription key and location. Both are correct. 
3) The result of (listCustomModels.transform(emptyDf)).show() is still empty

Thanks

**Comment by alidavoudian** [comment]
> I'll reach out to the team and schedule a meeting. In the meantime, could you double check your subscription key and location is correct? And could you double check the result of calling `listCustomModels.transform(emptyDf)` directly to see if it's also empty?

**Comment by alidavoudian** [comment]
> * I did check they subscription key and location. Both are correct.
> * The result of (listCustomModels.transform(emptyDf)).show() is still empty

I did check they subscription key and location. Both are correct.
The result of (listCustomModels.transform(emptyDf)).show() is still empty

**Comment by alidavoudian** [comment]
> 1. I sent the request to [negust@microsoft.com](mailto:negust@microsoft.com)

I sent the request to [negust@microsoft.com](mailto:negust@microsoft.com)
