### ISSUE TITLE
LightGBM, should I setNumThreads to number of total cores, or cores per executor ?

### ISSUE THREAD

**Issue by ttpro1995** [microsoft/SynapseML#1552]
In source code, it said: 

```
  val numThreads = new IntParam(this, "numThreads",
    "Number of threads for LightGBM. For the best speed, set this to the number of real CPU cores.")
```
However, I want to clarify, should I set to total of cores (cores per executors x number of executors) or cores per executor ?

AB#1861366

**Comment by svotaw** [comment]
this is the number of threads per executor, which can be considered a constant regardless of how many machines in your cluster (so **not** across all executors)

**Comment by svotaw** [comment]
https://github.com/microsoft/SynapseML/pull/1559
