### ISSUE TITLE
LightGBM: How to print the training process

### ISSUE THREAD

**Issue by sunkun1997** [microsoft/SynapseML#1554]
In the LightGBM Python package, I can set the lightgbm.log_evaluation parameter to see the training process. But in Synapaseml.lightgbm, I can't see anything. How can I see the training process just like the LightGBM Python package.

Looking forward to your reply

AB#1862983

**Comment by imatiach-msft** [comment]
@sunkun1997 you can view the logs we print out to log4j (which goes to SparkUI if you are using databricks), and also other logs to standard out and standard error on each of the worker nodes.  We will be adding more information in the future as well.  If there is some specific information that you need, please let us know, and we can look into adding it.  I agree that having parity with lightgbm python package would be a good goal for us to start with - which requires some investigation from our side.

**Comment by sunkun1997** [comment]
Thank you for your reply!

I had set the verbosity parameter to 100, and I found the following log from SparkUI
"""
[LightGBM] [Debug] Trained a tree with leaves = 21 and depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 21 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 21 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 21 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 21 and depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 21 and depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 21 and depth = 9
...
"""
I can't understand what it means.

However, when I use the Lightgbm Python package, The following logs are displayed
"""
Training until validation scores don't improve for 300 rounds
[100]	training's auc: 0.773026	valid_1's auc: 0.768707
[200]	training's auc: 0.777835	valid_1's auc: 0.771484
[300]	training's auc: 0.781997	valid_1's auc: 0.773566
[400]	training's auc: 0.785775	valid_1's auc: 0.775135
[500]	training's auc: 0.789288	valid_1's auc: 0.776261
[600]	training's auc: 0.792553	valid_1's auc: 0.776969
[700]	training's auc: 0.795541	valid_1's auc: 0.777435
...
"""
Through this log, I can know the training process very clearly. 

So I want to know how to get such logs.

**Comment by svotaw** [comment]
I am not sure exactly, but those logs appear to be added by the LightGbm python code itself (and in searching the LightGBM repo, I only see those kinds of logs in python/R code).  We use the underlying native C++ code directly, and we manage the iterations in our SynapseML layer in a custom way.  So it just sounds like you want us to add logs around each iteration.  Is that correct?  If so, can you be specific about what log information you want to see?

**Comment by sunkun1997** [comment]
@svotaw All right, I do want to see logs around each iteration, This seems to be done through Python by your answer. 

Anyway, thank you very much for your answer, Expect to see such logs in the future.

**Comment by svotaw** [comment]
We are adding more logs soon, but for now, I realized we also have the LightGBMDelegate.  This is a hook that allows you to do custom things at various stages. (e.g. extra logging if you want between iterations).  Check out LightGBMDelegate, and setDelegate() on the LightGBMClassifier (or whatever model you are using).  You might be able to get exactly what you want.

**Comment by ppruthi** [comment]
@sunkun1997 - If you feel your question has been answered, can you close the issue ? Else, feel free to comment further.

**Comment by stupidoge** [comment]
@svotaw Hi Scott, have you solved this kind of issues? Now LightGBMDelegate is deprecated.

**Comment by vividjulie** [comment]
Hi all,
I saw this issue was closed a while ago, but I’m still running into the same problem with LightGBMDelegate being deprecated. Has anyone figured out a fix or workaround yet to be able to print the training process?
Would really appreciate any updates! Thanks!
