### ISSUE TITLE
LASSO REGRESSION WITH PYSPARK Error

### ISSUE THREAD

**Issue by kelvin-thegreat** [microsoft/SynapseML#1585]
![Github-ML](https://user-images.githubusercontent.com/71261868/180738096-ddeac9de-c85d-41ce-8717-29dc3732bdaf.png)IllegalArgumentException                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_656/1060968647.py in <module>
----> 1 model = lasso.fit(train_lasso)

C:\spark-3.0.3-bin-hadoop2.7\python\pyspark\ml\base.py in fit(self, dataset, params)
    127                 return self.copy(params)._fit(dataset)
    128             else:
--> 129                 return self._fit(dataset)
    130         else:
    131             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

C:\spark-3.0.3-bin-hadoop2.7\python\pyspark\ml\wrapper.py in _fit(self, dataset)
    319 
    320     def _fit(self, dataset):
--> 321         java_model = self._fit_java(dataset)
    322         model = self._create_model(java_model)
    323         return self._copyValues(model)

C:\spark-3.0.3-bin-hadoop2.7\python\pyspark\ml\wrapper.py in _fit_java(self, dataset)
    316         """
    317         self._transfer_params_to_java()
--> 318         return self._java_obj.fit(dataset._jdf)
    319 
    320     def _fit(self, dataset):

C:\spark-3.0.3-bin-hadoop2.7\python\lib\py4j-0.10.9-src.zip\py4j\java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

C:\spark-3.0.3-bin-hadoop2.7\python\pyspark\sql\utils.py in deco(*a, **kw)
    132                 # Hide where the exception came from that shows a non-Pythonic
    133                 # JVM exception message.
--> 134                 raise_from(converted)
    135             else:
    136                 raise

C:\spark-3.0.3-bin-hadoop2.7\python\pyspark\sql\utils.py in raise_from(e)

IllegalArgumentException: features does not exist. Available: predictors, life

AB#1895276

**Comment by serena-ruan** [comment]
Hi @kelvin-thegreat, from the stacktrace you need to specify your featuresCol, the default value is "features", and it can't find this column in your dataframe so throwing this error. BTW, kindly remind this Logistic Regression API belongs to pyspark library, not SynapseML 😄

**Comment by serena-ruan** [comment]
Closing this as haven't heard back from the user for 10 days. Feel free to reopen once you have more questions :)
