### ISSUE TITLE
How do I add weight parameters in Lightgbm

### ISSUE THREAD

**Issue by sunkun1997** [microsoft/SynapseML#1642]
There seems to be no 'scale_pos_weight' parameter in synapse.ml. Lightgbm. How do I set weight parameters?

AB#1960925

**Comment by svotaw** [comment]
If there is a lightgbm parameter that SynapseMl has not explicitly exposed with a setter, you can use the generic setPassThroughArgs() to set your own values to pass directly to LightGBM.  Does this help?

https://github.com/microsoft/SynapseML/blob/8d552746951ab4190e82dda1d4f04699fc46c69f/lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/params/LightGBMParams.scala#L16

**Comment by svotaw** [comment]
note that for python this is passThroughArgs="scale_pos_weight=x".

closing this issue for now.  if you have further questions please reopen it or a new one.
