### ISSUE TITLE
[QUESTION] where is the source code of python LightGBMClassifier?

### ISSUE THREAD

**Issue by songhappy** [microsoft/SynapseML#1648]
In the document, I can see LightGBMClassifier and LightGBMClassificationModel, in here. 
https://mmlspark.blob.core.windows.net/docs/0.10.0/pyspark/_modules/synapse/ml/lightgbm/LightGBMClassifier.html#LightGBMClassifier
However, I can not find LightGBMClassifier on git, it only has LightGBMClassificationModel
https://github.com/microsoft/SynapseML/tree/master/lightgbm/src/main/python/synapse/ml/lightgbm.

How can I pull the code of python LightGBMClassifier? including the implementation and testcases? 

AB#1973054

**Comment by svotaw** [comment]
The LightGBMClassifier is here: https://github.com/microsoft/SynapseML/blob/master/lightgbm/src/main/scala/com/microsoft/azure/synapse/ml/lightgbm/LightGBMClassifier.scala

Note that most of SynapseML is written in Scala.  The python code for the most part is just a wrapper around Scala code, and is largely auto-generated. Test cases are at: https://github.com/microsoft/SynapseML/blob/master/lightgbm/src/test/scala/com/microsoft/azure/synapse/ml/lightgbm/split1/VerifyLightGBMClassifier.scala

**Comment by svotaw** [comment]
also, please use version 0.10.1 if you can. 0.10.0 has some model loading issues that have been fixed.

**Comment by svotaw** [comment]
Closing this issue as answered. Please reopen for more questions.

**Comment by songhappy** [comment]
> also, please use version 0.10.1 if you can. 0.10.0 has some model loading issues that have been fixed.

how about 0.9.5
