### ISSUE TITLE
Is there a way to get the jar file for synapseml ?

### ISSUE THREAD

**Issue by littlegirl6688** [microsoft/SynapseML#1655]
Is there a way to get the jar file for synapseml ?  The repositories: "https://mmlspark.azureedge.net/maven" does not exist anymore and I could not file the jar file anywhere. Please let me know if we can download it somewhere. Thank you!

AB#1983806

**Comment by serena-ruan** [comment]
Hi @littlegirl6688 , you could install any version of SynapseML by specifying the repository resolver as "https://mmlspark.azureedge.net/maven". Detailed installation guidance can be found on the bottom of the [website](https://microsoft.github.io/SynapseML/).
If you mean that you want to manually download just the jar, we only support downloading official versions from maven central: https://search.maven.org/artifact/com.microsoft.azure/synapseml_2.12

**Comment by SAMYAYYA** [comment]
[https://repo1.maven.org/maven2/com/microsoft/azure/synapseml_2.12/1.0.10/]

this is link for the downloading the synapseml
