### ISSUE TITLE
[BUG]'java.lang.NoClassDefFoundError: ai/onnxruntime/NodeInfo'

### ISSUE THREAD

**Issue by julia-pp** [microsoft/SynapseML#1682]
### SynapseML version

0.10.1

### System information

- **Language version**:  python 3.8, scala 2.12
- **Spark Version**:  3.2.0
- **Spark Platform**: Local on mac M1

### Describe the problem

When I want to use onnx inference on spark, it throws a 'java.lang.NoClassDefFoundError: ai/onnxruntime/NodeInfo' error.
I clone the raw source and don't find 'NodeInfo' definition in the project which used in https://github.com/microsoft/SynapseML/blob/master/deep-learning/src/main/scala/com/microsoft/azure/synapse/ml/onnx/ONNXModel.scala

### Code to reproduce issue

```
        spark = pyspark.sql.SparkSession.builder.appName("MyApp") \
        .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.10.1") \
        .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
        .getOrCreate()

        onnx_model = onnx.load(os.getcwd()+ '/data/lgb_single.onnx')

        from synapse.ml.onnx import ONNXModel

        onnx_ml = ONNXModel().setModelPayload(onnx_model.SerializeToString())

        # print("Model inputs:" + str(onnx_ml.getModelInputs()))
        # print("Model outputs:" + str(onnx_ml.getModelOutputs()))

        onnx_ml = (
            onnx_ml.setDeviceType("CPU")
                .setFeedDict({"input": "features"})
                .setFetchDict({"probability": "probabilities", "prediction": "label"})
                .setMiniBatchSize(1000)
        )
```

### Other info / logs

```
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: ai/onnxruntime/NodeInfo
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at py4j.reflection.ReflectionEngine.getMethodsByNameAndLength(ReflectionEngine.java:345)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:305)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ai.onnxruntime.NodeInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 12 more
```

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [X] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [X] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [X] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by memoryz** [comment]
Hi @julia-pp, this issue is because we depend on this library: `"com.microsoft.onnxruntime" % "onnxruntime_gpu" % "1.8.1"`, and it is not supported on MacOS.
To work around this problem, you can fork the code base, and swap out the dependency with CPU flavor: 
https://github.com/microsoft/SynapseML/blob/f29318a274610dda543ee1422bdbd74cdb6a752a/build.sbt#L406
replace it with `"com.microsoft.onnxruntime" % "onnxruntime" % "1.8.1"`.

To build the source code, you can follow the instructions here: https://github.com/microsoft/SynapseML/blob/master/website/docs/reference/developer-readme.md
