### ISSUE TITLE
[BUG] Generated Python code isn't consistent with Scala code

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/SynapseML#1702]
### SynapseML version

0.10.1

### System information

- python 3.8, scala 2.12:
- 3.2.2:
- Synapse

### Describe the problem

I found this issue that generated Python API is different with Scala's, and finally I realized that it uses parameter name rather than function name in code generation process.

For example, if I have this Scala code, in Scala I got API setOutcomeCol and getOutcomCol, but generated Python API are setOutcome and getOutcome, in my opinion, outcome param is an internal thing, no matter what name I use for it, Scala and Python should have the same APIs. 

### Code to reproduce issue

```scala
trait HasOutcomeCol extends Params {
  val outcome: Param[String] = new Param[String](this, "outcome", "outcome column")
  def getOutcomeCol: String = $(outcome)
  def setOutcomeCol(value: String): this.type = set(outcome, value)
}
```

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [ ] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by svotaw** [comment]
@mhamilton723  Can you comment on this?

**Comment by serena-ruan** [comment]
@dylanw-oss I think this is by design, because it's natural that if you have a param named paramA, the setter & getter should be named as setParamA & getParamA instead of setParamACol or getParamACol. If you use this parameters as the column for paramA you should name it as paramACol from the beginning to make it consistent.

**Comment by dylanw-oss** [comment]
I agreed it, thanks, serena!
