### ISSUE TITLE
Does synapse ml lightgbm support mleap serialization

### ISSUE THREAD

**Issue by Usmaniatech** [microsoft/SynapseML#1742]
Does synapse ml lightgbm support mleap serialization. If not, what type does this support ?

**Comment by JessicaXYWang** [comment]
@svotaw Could you take a look on this question? Thanks.

**Comment by Usmaniatech** [comment]
> @svotaw Could you take a look on this question? Thanks.

??

**Comment by svotaw** [comment]
Can you give a little more detail about the use case and context?  I'm not familiar with mleap. SynapseML LightGBM models can be serialized in either Spark (save) or native LightGBM format (saveNativeModel) and can be included in pipelines. I would think mlflow serialization of pipelines would be external to usage in SynapseML LightGBM, but I have not done any work in that area.

@mhamilton723 or @imatiach-msft for potentially more knowledge about integration with mleap.

If it's not something we support now, we can look into adding it.

**Comment by svotaw** [comment]
From mhamilton723:

"No, we don't support MLeap, but a user can save the native LGBM model for use in a single-threaded inference environment"
