### ISSUE TITLE
[BUG] publishBlob doesn't work with reading secret from environment variable

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/SynapseML#1782]
### SynapseML version

0.10.2

### System information

- **Language version** (e.g. python 3.8, scala 2.12):
- **Spark Version** (e.g. 3.2.3):
- **Spark Platform** (e.g. Synapse, Databricks):

### Describe the problem

1. Before executing command "publishBlob", set storage secret to environment variable
~ export STORAGE-KEY=<secret>
export: not valid in this context: STORAGE-KEY

the problem is that hyphen is not allowed in environment variable name.
all env names are defined in https://github.com/microsoft/SynapseML/blob/master/project/Secrets.scala
it's better to switch them to use underscore in name.

for example: 

val StorageKeyEnvVarName: String = "STORAGE-KEY"
==> 
val StorageKeyEnvVarName: String = "STORAGE_KEY"

### Code to reproduce issue

N/A

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [ ] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by niehaus59** [comment]
Hi @dylanw-oss.  When you set environment variables from the names listed in Secrets.com, just convert hyphens to underscores. In your particular case, publishBlob is run as a side effect of running "azp run".  That is, leave a comment in a PR that reads "azp run". This will force a build in our internal Azure Devops pipeline, and as a part of that build, publishBlob will be run.

**Comment by svotaw** [comment]
closing this as we really design publishing to work through the pipeline, and not through local Linux environments.

**Comment by dylanw-oss** [comment]
I need local publish to get private build for integration test.

I did it by using command "az login" and "sbt publishBlob" previously.
But for some reason (recent code changes?), this doesn't work anymore.

**Comment by mhamilton723** [comment]
For others that run into this issue the fix was to run `az account -s OUR_SUBSCRIPTION_ID` prior to running the build
