### ISSUE TITLE
[Question] Spark 2.4 Compatibility

### ISSUE THREAD

**Issue by farrokhsiar** [microsoft/SynapseML#1819]
I am wondering if has anyone tried to run SynapseML on Spark 2.4 to find out the possible incompatibility. Or is there any specific installations that make SynapseML compatible with Spark 2.4.

**Comment by serena-ruan** [comment]
Hi @farrokhsiar for spark2.4 version installation please see the response in this issue: https://github.com/microsoft/SynapseML/issues/1411
