### ISSUE TITLE
[BUG] LightGBMRegressor org.apache.spark.SparkException: Job aborted due to stage failure

### ISSUE THREAD

**Issue by RashidBakirov** [microsoft/SynapseML#1860]
### SynapseML version

0.10.2

### System information

- **Language version**: python 3.9.5
- **Spark Version**: 3.3.0
- **Spark Platform**: Databricks

### Describe the problem

I have a training dataset of about 6M rows and 205 columns (there are more in the original dataset, but I am using only the numeric ones as the output of VectorAssembler for training). The fitting fails with the error below. Any ideas on how to solve this?

### Code to reproduce issue

```
from synapse.ml.lightgbm import LightGBMRegressor
from pyspark.ml.feature import VectorAssembler

numeric_cols = [col_name for col_name, col_type in df.dtypes if col_type != 'string']

target = 'target_feature'
numeric_cols.remove(target)

featurizer = VectorAssembler(inputCols=numeric_cols, outputCol="features")
train_data = featurizer.transform(df_train)[target, "features"] #df_train and test are created beforehand by splitting df
test_data = featurizer.transform(df_test)[target, "features"]

model = LightGBMRegressor(objective="quantile", featuresCol="features", labelCol=target,useSingleDatasetMode=True,useBarrierExecutionMode=True)
#have also tried without last two arguments

model=model.fit(train_data)
```

### Other info / logs

```org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 286.0 failed 4 times, most recent failure: Lost task 0.3 in stage 286.0 (TID 867) (10.121.1.6 executor driver): org.apache.spark.SparkException: [FAILED_EXECUTE_UDF] Failed to execute user defined function (VectorAssembler$$Lambda$9794/269023659: (struct<years_double_VectorAssembler_97446de2eba8:double,month_double_VectorAssembler_97446de2eba8:double,month_lag_1_double_VectorAssembler_97446de2eba8:double,month_lag_2_double_VectorAssembler_97446de2eba8:double,month_lag_3_double_VectorAssembler_97446de2eba8:double,month_lag_avg:double... [ALL FEATURES ARE LISTED] => struct<type:tinyint,size:int,indices:array<int>,values:array<double>>)```

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [ ] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by RashidBakirov** [comment]
That could be because I passed null values to VectorAssembler.

What is the proper way to deal with nulls for SynapseML LGBM?

**Comment by RashidBakirov** [comment]
@imatiach-msft @mhamilton723 @memoryz - any ideas please?

**Comment by memoryz** [comment]
I'm not sure what exactly the cause is here, but Spark vectors do not allow null values.  Maybe try imputing the null values first? At least this tells you whether the issue is caused by null values.

**Comment by memoryz** [comment]
My suggestion is to run some exploratory data analysis and try to understand what the null values indicate. If these values are not the result of upstream data processing error, and truly represent unknown data, impute them with a special value that can represent unknown.
