### ISSUE TITLE
DML .setFitIntercept should be set to true in final stage linear model

### ISSUE THREAD

**Issue by sarahshy** [microsoft/SynapseML#1869]
https://github.com/microsoft/SynapseML/blob/62c79d84d9999a618a596a03bab12dfad05114ce/core/src/main/scala/com/microsoft/azure/synapse/ml/causal/DoubleMLEstimator.scala#L259 

Currently .setFitIntercept is set to false, which will force the intercept to be 0. This should be changed to true as it may change the estimate for the slope in the residuals linear model.

@dylanw-oss

**Comment by k-rush** [comment]
@mhamilton723 and @dylanw-oss, I see this issue has been addressed in #1876. Do we have a new build of the library that @sarahshy can use?

**Comment by dylanw-oss** [comment]
yes, the master branch build should have the fix, "com.microsoft.azure:synapseml-core_2.12:0.11.0-19-87e1c786-SNAPSHOT"

**Comment by k-rush** [comment]
@sarahshy can you try using this new build?

"com.microsoft.azure:synapseml-core_2.12:0.11.0-19-87e1c786-SNAPSHOT"

**Comment by dylanw-oss** [comment]
we can close this issue on behalf of Sarah.
