### ISSUE TITLE
Synapse ML support for OpenAIChatCompletion Apache Spark Client

### ISSUE THREAD

**Issue by Fawziya** [microsoft/SynapseML#1913]
**Is your feature request related to a problem? Please describe.**
GPT-4 model only works with ChatCompletion API. When calling GPT-4 model using existing OpenAICompletion API, receiving following error "The completion operation does not work with the specified model, gpt-4. Please choose different model and try again."

**Describe the solution you'd like**
Feature ask for SynpaseML's support for OpenAIChatCompletion Apache Spark Client in order to use GPT-4 model.

**Comment by mhamilton723** [comment]
Thank you for your interest! Please use latest master to access the
OpenAIChatCompletion API. We will cut a new minor version (0.11.1) with
these changes too.

SynapseML Build and Release Information
Maven Coordinates

com.microsoft.azure:synapseml_2.12:0.11.0-40-469445b7-SNAPSHOT
Maven Resolver

https://mmlspark.azureedge.net/maven
Documentation Pages:

Scala Documentation
<https://mmlspark.blob.core.windows.net/docs/0.11.0-40-469445b7-SNAPSHOT/scala/index.html>

Python Documentation
<https://mmlspark.blob.core.windows.net/docs/0.11.0-40-469445b7-SNAPSHOT/pyspark/index.html>

**Comment by Fawziya** [comment]
Awesome! Will try offline.
Close the request as the request is already taken by the team.
