### ISSUE TITLE
Feature engineering support in SynapseML

### ISSUE THREAD

**Issue by vishalovercome** [microsoft/SynapseML#1955]
I'm evaluating SynapseML as the framework for all our machine learning use cases. What I find appealing is the wide variety of algorithms as well as distributed data processing frameworks that are supported by this project. However I couldn't find much documentation on the level of support for feature selection and support for transformations seems limited as well. If there is extensive support for it, then can you share the documentation? If this framework intended as a starter framework to get things going then can you share the roadmap and design philosophy of this project so that we know what to expect. Or is it that this framework is intended to be used for just the final algorithm and perhaps explainability and portability (onnx) while feature engineering is expected to be done by the underlying distributed data processing framework such as Spark?

**Comment by ppruthi** [comment]
Hey @vishalovercome --- thanks for reaching out and your comments.
@mhamilton723 might be able to provide you a holistic answer to your question.

**Comment by vishalovercome** [comment]
@ppruthi / @mhamilton723 - any updates here?
