### ISSUE TITLE
[BUG] Unable to install in AWS EMR cluster

### ISSUE THREAD

**Issue by vishalovercome** [microsoft/SynapseML#1958]
### SynapseML version

0.11.1

### System information

- **Language version** : python 3.8, scala 2.12
- **Spark Version** : 3.2.1
- **Spark Platform** : JupyterLab notebook running on AWS Elastic Map Reduce (client mode)

### Describe the problem

I'm able to install synapseml version 0.11.1 using the instructions in the doc. However the same doesn't work when I run the same notebook in AWS EMR environment. Differences in the environment s are:

1. Kernel - Python (local) vs PySpark (AWS EMR)
2. OS - Mac (local) vs. Amazon Linux (fedora based)

I've tried v0.10.2 and setting "spark.databricks.libraries.enableMavenResolution" to False as suggested in some other threads but neither of that helped.

### Code to reproduce issue

```python
spark: SparkSession = (
    SparkSession.builder
    .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.11.1")
    .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven")
    .config("spark.jars.packages", "org.mlflow:mlflow-spark:1.14.0") 
    .config("spark.sql.shuffle.partitions", 1000)
    .config("spark.dynamicAllocation.executorIdleTimeout", 600)
    .config("spark.default.parallelism", 1000)
    .config("spark.sql.adaptive.enabled", True)
    .config("spark.sql.adaptive.coalescePartitions.enabled", True)
    .enableHiveSupport()
    .getOrCreate()
)

sc: SparkContext = spark.sparkContext
spark.sparkContext.getConf().get("spark.driver.memory")
spark.conf.set("spark.sql.adaptive.enabled", True)
spark.conf.set("spark.sql.adaptive.coalescePartitions.enabled", True)

import synapse.ml
```

### Other info / logs

SparkSession available as 'spark'.

An error was encountered:
No module named 'synapse'
Traceback (most recent call last):
ModuleNotFoundError: No module named 'synapse'

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [ ] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [X] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [ ] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by vishalovercome** [comment]
In my local environment, I didn't have to explicitly install synapseml using pip and I hope that's not the problem here. Will explicitly installing it and using allow for Spark integration as well? I'm not sure how and where the JAR will be installed and picked up by Spark

**Comment by vishalovercome** [comment]
Pretty sure pip install is not the right thing to do. I tried running my code in a notebook environment and got this error: 

```python-traceback
'JavaPackage' object is not callable
Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "<stdin>", line 533, in train
  File "<stdin>", line 407, in build_model
  File "<stdin>", line 5, in light_gbm
  File "/mnt1/yarn/usercache/livy/appcache/application_1684366043257_0001/container_1684366043257_0001_01_000001/pyspark.zip/pyspark/__init__.py", line 114, in wrapper
    return func(self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/synapse/ml/lightgbm/LightGBMClassifier.py", line 398, in __init__
    self._java_obj = self._new_java_obj("com.microsoft.azure.synapse.ml.lightgbm.LightGBMClassifier", self.uid)
  File "/mnt1/yarn/usercache/livy/appcache/application_1684366043257_0001/container_1684366043257_0001_01_000001/pyspark.zip/pyspark/ml/wrapper.py", line 66, in _new_java_obj
    return java_obj(*java_args)
TypeError: 'JavaPackage' object is not callable
```

**Comment by vishalovercome** [comment]
I've also tried to install this in pyspark 3.3 using instructions in #1961 but it doesn't work. I've tried downgrading to python 3.7 and that didn't help either

**Comment by vishalovercome** [comment]
Thanks a lot @JessicaXYWang! This seems to have worked. Though its strange because I did try to do this with pyspark-3.2.1 and synapse-0.11.1 and it somehow didn't at that time. 

Anyhow, a Spark upgrade shouldn't be a problem for us. Only question I have for you now is whether a simple spark submit with the jars will work like so:

`pyspark --packages com.microsoft.azure:synapseml_2.12:0.11.1-spark3.3`

or whether we need to have to configure EMR differently at the time of spawning clusters

**Comment by vishalovercome** [comment]
@JessicaXYWang can we use this spark 3.3 package in spark 3.4 also? we have to run on 3.4 as it has some critical bug fixes

**Comment by vishalovercome** [comment]
@JessicaXYWang I get the following fatal error when trying to train a model:

`An error was encountered:
Interpreter died:

/mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/pyspark.zip/pyspark/context.py:348: RuntimeWarning: Failed to add file [file:///mnt/var/lib/livy/.ivy2/jars/com.microsoft.azure_synapseml_2.12-0.11.1-spark3.3.jar] specified in 'spark.submit.pyFiles' to Python path:
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/tmp
  /mnt1/yarn/usercache/livy/appcache/application_1687341854481_0001/spark-779a7512-d7bd-48d0-92a1-67ca6bcc9874/userFiles-77c6e4ed-14ee-4cea-b469-b711b0bac83a
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/pyspark.zip
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/py4j-0.10.9.5-src.zip
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml_2.12-0.11.1-spark3.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-core_2.12-0.11.1-spark3.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-deep-learning_2.12-0.11.1-spark3.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-cognitive_2.12-0.11.1-spark3.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-vw_2.12-0.11.1-spark3.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-lightgbm_2.12-0.11.1-spark3.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-opencv_2.12-0.11.1-spark3.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scalactic_scalactic_2.12-3.2.14.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/io.spray_spray-json_2.12-1.3.5.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.jcraft_jsch-0.1.54.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents.client5_httpclient5-5.1.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents_httpmime-4.5.13.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.linkedin.isolation-forest_isolation-forest_3.2.0_2.12-2.0.8.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scalanlp_breeze_2.12-1.2.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scala-lang_scala-reflect-2.12.15.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents.core5_httpcore5-5.1.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents.core5_httpcore5-h2-5.1.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.slf4j_slf4j-api-1.7.25.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/commons-codec_commons-codec-1.15.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents_httpclient-4.5.13.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents_httpcore-4.4.13.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/commons-logging_commons-logging-1.2.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.spark_spark-avro_2.12-3.2.0.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.testng_testng-6.8.8.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_macro-compat_2.12-1.1.1.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.tukaani_xz-1.8.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.spark-project.spark_unused-1.0.0.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.beanshell_bsh-2.0b4.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.beust_jcommander-1.27.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scalanlp_breeze-macros_2.12-1.2.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.github.fommil.netlib_core-1.1.2.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/net.sourceforge.f2j_arpack_combined_all-0.1-javadoc.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/net.sourceforge.f2j_arpack_combined_all-0.1.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/net.sf.opencsv_opencsv-2.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.github.wendykierp_JTransforms-3.1.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.commons_commons-math3-3.2.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.chuusai_shapeless_2.12-2.3.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_spire_2.12-0.17.0.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scala-lang.modules_scala-collection-compat_2.12-2.1.1.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/pl.edu.icm_JLargeArrays-1.5.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_spire-macros_2.12-0.17.0.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_spire-platform_2.12-0.17.0.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_spire-util_2.12-0.17.0.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_algebra_2.12-2.0.1.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_cats-kernel_2.12-2.1.1.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_onnx-protobuf_2.12-0.9.3.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.onnxruntime_onnxruntime_gpu-1.8.1.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.openpnp_opencv-3.2.0-1.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.cognitiveservices.speech_client-jar-sdk-1.14.0.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.github.vowpalwabbit_vw-jni-9.3.0.jar
  /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.ml.lightgbm_lightgbmlib-3.3.500.jar
  /usr/lib64/python38.zip
  /usr/lib64/python3.8
  /usr/lib64/python3.8/lib-dynload
  /usr/local/lib64/python3.8/site-packages
  /usr/local/lib/python3.8/site-packages
  /usr/lib64/python3.8/site-packages
  /usr/lib/python3.8/site-packages
  warnings.warn(

WARNING:matplotlib:Matplotlib created a temporary config/cache directory at /tmp/matplotlib-je0aoibi because the default path (/home/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.`

What do you suggest?

**Comment by JessicaXYWang** [comment]
@mhamilton723 Hi Mark, can you help with this question? Thank you.

**Comment by mhamilton723** [comment]
> @JessicaXYWang I get the following fatal error when trying to train a model:
> 
> ```
> An error was encountered:
> Interpreter died:
> 
> /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/pyspark.zip/pyspark/context.py:348: RuntimeWarning: Failed to add file [file:///mnt/var/lib/livy/.ivy2/jars/com.microsoft.azure_synapseml_2.12-0.11.1-spark3.3.jar] specified in 'spark.submit.pyFiles' to Python path:
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/tmp
>   /mnt1/yarn/usercache/livy/appcache/application_1687341854481_0001/spark-779a7512-d7bd-48d0-92a1-67ca6bcc9874/userFiles-77c6e4ed-14ee-4cea-b469-b711b0bac83a
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/pyspark.zip
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/py4j-0.10.9.5-src.zip
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml_2.12-0.11.1-spark3.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-core_2.12-0.11.1-spark3.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-deep-learning_2.12-0.11.1-spark3.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-cognitive_2.12-0.11.1-spark3.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-vw_2.12-0.11.1-spark3.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-lightgbm_2.12-0.11.1-spark3.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_synapseml-opencv_2.12-0.11.1-spark3.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scalactic_scalactic_2.12-3.2.14.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/io.spray_spray-json_2.12-1.3.5.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.jcraft_jsch-0.1.54.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents.client5_httpclient5-5.1.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents_httpmime-4.5.13.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.linkedin.isolation-forest_isolation-forest_3.2.0_2.12-2.0.8.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scalanlp_breeze_2.12-1.2.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scala-lang_scala-reflect-2.12.15.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents.core5_httpcore5-5.1.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents.core5_httpcore5-h2-5.1.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.slf4j_slf4j-api-1.7.25.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/commons-codec_commons-codec-1.15.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents_httpclient-4.5.13.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.httpcomponents_httpcore-4.4.13.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/commons-logging_commons-logging-1.2.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.spark_spark-avro_2.12-3.2.0.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.testng_testng-6.8.8.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_macro-compat_2.12-1.1.1.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.tukaani_xz-1.8.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.spark-project.spark_unused-1.0.0.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.beanshell_bsh-2.0b4.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.beust_jcommander-1.27.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scalanlp_breeze-macros_2.12-1.2.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.github.fommil.netlib_core-1.1.2.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/net.sourceforge.f2j_arpack_combined_all-0.1-javadoc.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/net.sourceforge.f2j_arpack_combined_all-0.1.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/net.sf.opencsv_opencsv-2.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.github.wendykierp_JTransforms-3.1.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.apache.commons_commons-math3-3.2.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.chuusai_shapeless_2.12-2.3.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_spire_2.12-0.17.0.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.scala-lang.modules_scala-collection-compat_2.12-2.1.1.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/pl.edu.icm_JLargeArrays-1.5.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_spire-macros_2.12-0.17.0.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_spire-platform_2.12-0.17.0.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_spire-util_2.12-0.17.0.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_algebra_2.12-2.0.1.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.typelevel_cats-kernel_2.12-2.1.1.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.azure_onnx-protobuf_2.12-0.9.3.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.onnxruntime_onnxruntime_gpu-1.8.1.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/org.openpnp_opencv-3.2.0-1.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.cognitiveservices.speech_client-jar-sdk-1.14.0.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.github.vowpalwabbit_vw-jni-9.3.0.jar
>   /mnt/yarn/usercache/livy/appcache/application_1687341854481_0001/container_1687341854481_0001_01_000001/com.microsoft.ml.lightgbm_lightgbmlib-3.3.500.jar
>   /usr/lib64/python38.zip
>   /usr/lib64/python3.8
>   /usr/lib64/python3.8/lib-dynload
>   /usr/local/lib64/python3.8/site-packages
>   /usr/local/lib/python3.8/site-packages
>   /usr/lib64/python3.8/site-packages
>   /usr/lib/python3.8/site-packages
>   warnings.warn(
> 
> WARNING:matplotlib:Matplotlib created a temporary config/cache directory at /tmp/matplotlib-je0aoibi because the default path (/home/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
> ```
> 
> 1. Is it a case of conflicting dependencies? How to figure out?
> 2. Is the matplotlib warning a separate issue?
> 3. How to move forward?

With regard to this issue we'll need some more info. In particular are you trying to run one of our samples? If so try removing the matplotlib code and seeing if it runs through. In general we'll want to try to find and isolate the culprit here

**Comment by vishalovercome** [comment]
Thanks for your reply. As of now, I'm currently blocked due to a glibc issue #1811 due to which I won't be able to run any code. Perhaps the above exception got thrown at an earlier stage but I will only get to this project once I have a full working setup. I'm a bit confused about this response of yours:

```
Yes this should work. If you need one specifically compiled against spark 3.3 try v0.11.1-spark3.3
```

Does this mean that we should use version v0.11.1 and NOT v0.11.1-spark3.3? I'm confused because if the former will work with 3.4 then why create v0.11.1-spark3.3?

**Comment by mhamilton723** [comment]
> Thanks for your reply. As of now, I'm currently blocked due to a glibc issue #1811 due to which I won't be able to run any code. Perhaps the above exception got thrown at an earlier stage but I will only get to this project once I have a full working setup. I'm a bit confused about this response of yours:
> 
> ```
> Yes this should work. If you need one specifically compiled against spark 3.3 try v0.11.1-spark3.3
> ```
> 
> Does this mean that we should use version v0.11.1 and NOT v0.11.1-spark3.3? I'm confused because if the former will work with 3.4 then why create v0.11.1-spark3.3?

Good question, we didnt have to really change much when updating to spark 3.3 so thats why either v0.11.1 or v0.11.1-spark3.3 works with 3.3 and 3.4. We just made   v0.11.1-spark3.3 to be extra cautious
