### ISSUE TITLE
Manual models and TabularSHAP

### ISSUE THREAD

**Issue by merhuhn** [microsoft/SynapseML#1986]
I am working on a ML solution that uses an ensemble approach to classification. We train two base models and combine them with other features in a final score with a random forest. I would love to implement explainability with TabularSHAP but the specifics of our use case mean this is tricky. We can run TabularSHAP on each model individually but I would love to implement a version that returns SHAP values on untransformed inputs. The SHAP values for the random forest return the two input model results as the most important features.

I tried to create a class that combines the two model predictions and scores with the random forest in a transform method. This method works when run independently but fails when used in TabularSHAP (I'm running into threadlock errors).

I am able to run a similar script with models created in sklearn and using the Python shap library and it does produce appropriate SHAP values for raw features.

Are there any recommended approaches for "manual" ensemble models in this context?

**Comment by memoryz** [comment]
Can you combine the three models in a PipelineModel and run TabularSHAP on that?

**Comment by merhuhn** [comment]
Yes, it looks like is possible to combine the models in a PipelineModel. I will have to change how I've trained the random forest since I would have to rely on a custom transformer in the PipelineModel to use it as it is currently set up. That version failed with an error: `object has no attribute '_to_java'`.
