### ISSUE TITLE
[BUG] FindBestModel selects the worst model instead of the best

### ISSUE THREAD

**Issue by pitch-r** [microsoft/SynapseML#1987]
### SynapseML version

0.11.1

### System information

- **Language version** (e.g. python 3.8, scala 2.12): python 3.8
- **Spark Version** (e.g. 3.2.3): 3.2.1
- **Spark Platform** (e.g. Synapse, Databricks): Databricks

### Describe the problem

Hello
I looked through the FindBestModel code in https://github.com/microsoft/SynapseML/blob/master/core/src/main/scala/com/microsoft/azure/synapse/ml/automl/FindBestModel.scala#L102

Looks like instead of finding the best model (highest value for AUC, accuracy, precision and etc.), it will set the model with the lowest value as the best model. (vice versa for loss metrics) 

https://github.com/microsoft/SynapseML/blob/master/core/src/main/scala/com/microsoft/azure/synapse/ml/automl/EvaluationUtils.scala#L58

`operator.gt() `on [line 102 ](https://github.com/microsoft/SynapseML/blob/master/core/src/main/scala/com/microsoft/azure/synapse/ml/automl/FindBestModel.scala#L102) should be `operator.lt()`

### Code to reproduce issue

val findBestModel = FindBestModel("AUC", ...)
findBestModel.fit(test)
findBestModel.getBestModelMetrics() 

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [X] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [X] `language/scala`: Scala source code
- [ ] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [ ] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by eisber** [comment]
@pitch-r  thanks for reporting!
