### ISSUE TITLE
[QUESTION] ONNX examples/support missing from SynapseML website/docs? 

### ISSUE THREAD

**Issue by brandongreenwell-8451** [microsoft/SynapseML#2028]
### SynapseML version

NA

### System information

- **Language version** (e.g. python 3.8, scala 2.12):
- **Spark Version** (e.g. 3.2.3):
- **Spark Platform** (e.g. Synapse, Databricks):

### Describe the problem

The ONNX support and examples seems to be missing from the docs/website. For example,

https://microsoft.github.io/SynapseML/docs/next/features/onnx/about/

### Code to reproduce issue

NA

### What component(s) does this bug affect?

- [ ] `area/cognitive`: Cognitive project
- [X] `area/core`: Core project
- [ ] `area/deep-learning`: DeepLearning project
- [ ] `area/lightgbm`: Lightgbm project
- [ ] `area/opencv`: Opencv project
- [ ] `area/vw`: VW project
- [ ] `area/website`: Website
- [ ] `area/build`: Project build system
- [ ] `area/notebooks`: Samples under notebooks folder
- [ ] `area/docker`: Docker usage
- [ ] `area/models`: models related issue

### What language(s) does this bug affect?

- [X] `language/scala`: Scala source code
- [X] `language/python`: Pyspark APIs
- [ ] `language/r`: R APIs
- [ ] `language/csharp`: .NET APIs
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/synapse`: Azure Synapse integrations
- [X] `integrations/azureml`: Azure ML integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by brandongreenwell-8451** [comment]
Looks like it was moved to the DeepLearning section? Is that to be expected?

**Comment by JessicaXYWang** [comment]
Hi @brandongreenwell-8451 , ONNX doc is now under Deep Learning section. Please check it [here](https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/Deep%20Learning/ONNX/)

**Comment by brandongreenwell-8451** [comment]
Thanks @JessicaXYWang, and sorry for the late reply. Is there a particular reason ONNX is moved under deep learning, as opposed to its own section? Curious since ONNX is much broader and support a lot of non-NN frameworks (e.g., EBMs, sklearn, etc.). In any case, I was able to find the docs in the new location.
