### ISSUE TITLE
It is unfortunate as repartiton is more expensive than coalesce.

### ISSUE THREAD

**Issue by JWenBin** [microsoft/SynapseML#923]
I find it is better to use "--master local[*]" than "--master yarn --num-executors 1 xxx" than “--master yarn --num-executors 20 xxx”, while training like “val lgbmModel: LightGBMClassificationModel =classifier.fit(trainDF)”, because of the difference utilization of CPU.
“--master yarn --num-executors 20 xxx”: My Linux using only about 20% of the cpu on each node.
"--master yarn --num-executors 1 xxx": My single node using about 50% of the cpu.
"--master local[*]": My master using about 99% of the cpu.
It seems the more executors I use the slower my training is. As it says “...which is unfortunate as repartiton is more expensive than coalesce.” at https://github.com/Azure/mmlspark/commit/9805996143d4cf174895ff2e08bb61fd2c99c4f1.
But I don't know why or how to faster my training.
Is there any one facing the same problem? 

Thx in advance!

**Comment by imatiach-msft** [comment]
@JWenBin this is an interesting observation - I think using 20 executors is reducing CPU to 20% due to network overhead, but I can't be sure.  I don't know why 1 vs local would make a difference.  Definitely seems like something that needs to be profiled and investigated more.

**Comment by JWenBin** [comment]
To avoid “FileNotFoundException...... (Too many open files)” while using "local[x]", I use a spark cluster with only 1 master and 1 slave. 
In order to make my CPU more effective, I submit my spark application like "spark-submit --deploy-mode cluster --master yarn --driver-cores 1 --driver-memory 6G --num-executors 1 --executor-memory 62G --executor-cores 46 --conf spark.driver.maxResultSize=4G --conf spark.dynamicAllocation.enabled=false ......". So that the spark application driver and executors are on the same spark slave. In this way, My single node using about 96% of the cpu.
By the way, I said  " --deploy-mode **client**--master yarn --num-executors 1 xxx": My single node using about 50% of the cpu. This is because the spark application driver and executors are not on the same spark slave.

@imatiach-msft How do you train your "LightGBMClassificationModel " with your spark cluster? Thx.

**Comment by JWenBin** [comment]
I tried the newest version today, and my CPU Utilization could be about 94% on each spark slave! Well done!!!

My cluster Info：
spark slave: 96 vCore, 192 GiB *3; 
spark version:  Spark 3.1.2, Hive 3.1.2, ZooKeeper 3.5.7
dependency:
```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>synapseml_2.12</artifactId>
            <version>0.9.4</version>
        </dependency>
```
submit info: spark-submit --master yarn --driver-cores 2 --driver-memory 2G --num-executors 6 --executor-memory 73G --executor-cores 48  --conf spark.dynamicAllocation.enabled=false --conf spark.default.parallelism=570 --jars s3://EMR/jars/jasypt-1.9.2.jar,s3://EMR/jars/spark-mllib_2.11-2.4.0.jar,s3://EMR/jars/jedis-2.9.0.jar,s3://EMR/jars/commons-pool2-2.0.jar,s3://EMR/jars/spray-json_2.12-1.3.2.jar,s3://EMR/jars/synapseml-lightgbm_2.12-0.9.4.jar,s3://EMR/jars/lightgbmlib-3.2.110.jar,s3://EMR/jars/synapseml-cognitive_2.12-0.9.4.jar,s3://EMR/jars/synapseml-core_2.12-0.9.4.jar,s3://EMR/jars/synapseml-deep-learning_2.12-0.9.4.jar,s3://EMR/jars/synapseml-vw_2.12-0.9.4.jar,s3://EMR/jars/synapseml_2.12-0.9.4.jar,s3://EMR/jars/client-sdk-1.14.0.jar  --class myClassName.TrainGbdt s3://EMR/jars/mySpark3-1.0.jar 

Thanks!!!
