### ISSUE TITLE
[LightGBM] Cannot set random seed value for LightGBM Classifier for reproducibility

### ISSUE THREAD

**Issue by isaac-gritz** [microsoft/SynapseML#928]
Unable set random seed value for LightGBM Classifier for reproducibility. Every other machine learning algorithm and machine learning library allows setting a random seed value.

**Comment by imatiach-msft** [comment]
closing as lightgbm is now deterministic with merged PR https://github.com/microsoft/SynapseML/pull/1387 as long as seed and deterministic=True parameters are set
